#!/data/data/com.termux/files/usr/bin/env python
import os
import sys
from pathlib import Path

MIME2EXT: dict = {
    "application/andrew-inset": [".ez"],
    "application/annodex": [".anx"],
    "application/appinstaller": [".appinstaller"],
    "application/applixware": [".aw"],
    "application/appx": [".appx"],
    "application/appxbundle": [".appxbundle"],
    "application/atom+xml": [".atom"],
    "application/atomcat+xml": [".atomcat"],
    "application/atomsvc+xml": [".atomsvc"],
    "application/cbor": [".cbor"],
    "application/ccxml+xml": [".ccxml"],
    "application/cdmi-capability": [".cdmia"],
    "application/cdmi-container": [".cdmic"],
    "application/cdmi-domain": [".cdmid"],
    "application/cdmi-object": [".cdmio"],
    "application/cdmi-queue": [".cdmiq"],
    "application/cu-seeme": [".cu"],
    "application/davmount+xml": [".davmount"],
    "application/dicom": [".dcm", ".dicomdir"],
    "application/docbook+xml": [".dbk"],
    "application/dssc+der": [".dssc"],
    "application/dssc+xml": [".xdssc"],
    "application/ecmascript": [".ecma", ".es"],
    "application/emma+xml": [".emma"],
    "application/epub+zip": [".epub"],
    "application/exi": [".exi"],
    "application/fits": [".fit", ".fits", ".fts"],
    "application/font-eot": [".eot"],
    "application/font-otf": [".otf"],
    "application/font-tdpfr": [".pfr"],
    "application/font-ttf": [".ttf"],
    "application/font-woff": [".woff"],
    "application/font-woff2": [".woff2"],
    "application/geo+json": [".geo.json", ".geojson"],
    "application/gml+xml": [".gml"],
    "application/gnunet-directory": [".gnd"],
    "application/gpx+xml": [".gpx"],
    "application/gxf": [".gxf"],
    "application/gzip": [".gz"],
    "application/hyperstudio": [".stk"],
    "application/illustrator": [".ai"],
    "application/inkml+xml": [".ink", ".inkml"],
    "application/ipfix": [".ipfix"],
    "application/its+xml": [".its"],
    "application/java-archive": [".jar"],
    "application/java-serialized-object": [".ser"],
    "application/java-vm": [".class"],
    "application/javascript": [".js"],
    "application/jrd+json": [".jrd"],
    "application/json": [".json"],
    "application/json-patch+json": [".json-patch"],
    "application/json5": [".json5"],
    "application/jsonml+json": [".jsonml"],
    "application/ld+json": [".jsonld"],
    "application/lost+xml": [".lostxml"],
    "application/mac-binhex40": [".hqx"],
    "application/mac-compactpro": [".cpt"],
    "application/mads+xml": [".mads"],
    "application/manifest+json": [".webmanifest"],
    "application/marc": [".mrc"],
    "application/marcxml+xml": [".mrcx"],
    "application/mathematica": [".ma", ".nb", ".mb"],
    "application/mathml+xml": [".mathml", ".mml"],
    "application/mbox": [".mbox"],
    "application/mediaservercontrol+xml": [".mscml"],
    "application/metalink+xml": [".metalink"],
    "application/metalink4+xml": [".meta4"],
    "application/mets+xml": [".mets"],
    "application/mods+xml": [".mods"],
    "application/mp21": [".m21", ".mp21"],
    "application/mp4": [".mp4s"],
    "application/msix": [".msix"],
    "application/msixbundle": [".msixbundle"],
    "application/msword": [".doc", ".dot"],
    "application/mxf": [".mxf"],
    "application/n-quads": [".nq"],
    "application/n-triples": [".nt"],
    "application/octet-stream": [
        ".bin",
        ".dms",
        ".lrf",
        ".mar",
        ".so",
        ".dist",
        ".distz",
        ".pkg",
        ".bpk",
        ".dump",
        ".elc",
        ".deploy",
    ],
    "application/oda": [".oda"],
    "application/oebps-package+xml": [".opf"],
    "application/ogg": [".ogx"],
    "application/omdoc+xml": [".omdoc"],
    "application/onenote": [".onetoc", ".onetoc2", ".onetmp", ".onepkg"],
    "application/ovf": [".ova"],
    "application/owl+xml": [".owx"],
    "application/oxps": [".oxps"],
    "application/patch-ops-error+xml": [".xer"],
    "application/pdf": [".pdf"],
    "application/pgp-encrypted": [".pgp"],
    "application/pgp-keys": [".asc", ".gpg", ".key", ".pkr", ".skr"],
    "application/pgp-signature": [".sig"],
    "application/pics-rules": [".prf"],
    "application/pkcs10": [".p10"],
    "application/pkcs12": [".p12", ".pfx"],
    "application/pkcs7-mime": [".p7m", ".p7c"],
    "application/pkcs7-signature": [".p7s"],
    "application/pkcs8": [".p8"],
    "application/pkcs8-encrypted": [".p8e"],
    "application/pkix-attr-cert": [".ac"],
    "application/pkix-cert": [".cer"],
    "application/pkix-crl": [".crl"],
    "application/pkix-pkipath": [".pkipath"],
    "application/pkixcmp": [".pki"],
    "application/pls+xml": [".pls"],
    "application/postscript": [".eps", ".ps"],
    "application/prs.cww": [".cww"],
    "application/pskc+xml": [".pskcxml"],
    "application/ram": [".ram"],
    "application/raml+yaml": [".raml"],
    "application/rdf+xml": [".rdf", ".owl", ".rdfs"],
    "application/reginfo+xml": [".rif"],
    "application/relax-ng-compact-syntax": [".rnc"],
    "application/resource-lists+xml": [".rl"],
    "application/resource-lists-diff+xml": [".rld"],
    "application/rls-services+xml": [".rs"],
    "application/rpki-ghostbusters": [".gbr"],
    "application/rpki-manifest": [".mft"],
    "application/rpki-roa": [".roa"],
    "application/rsd+xml": [".rsd"],
    "application/rss+xml": [".rss"],
    "application/rtf": [".rtf"],
    "application/sbml+xml": [".sbml"],
    "application/scvp-cv-request": [".scq"],
    "application/scvp-cv-response": [".scs"],
    "application/scvp-vp-request": [".spq"],
    "application/scvp-vp-response": [".spp"],
    "application/sdp": [".sdp"],
    "application/set-payment-initiation": [".setpay"],
    "application/set-registration-initiation": [".setreg"],
    "application/shf+xml": [".shf"],
    "application/sieve": [".sieve", ".siv"],
    "application/smil+xml": [".smi", ".smil", ".sml", ".kino"],
    "application/sparql-query": [".rq", ".qs"],
    "application/sparql-results+xml": [".srx"],
    "application/sql": [".sql"],
    "application/srgs": [".gram"],
    "application/srgs+xml": [".grxml"],
    "application/sru+xml": [".sru"],
    "application/ssdl+xml": [".ssdl"],
    "application/ssml+xml": [".ssml"],
    "application/tei+xml": [".tei", ".teicorpus"],
    "application/thraud+xml": [".tfi"],
    "application/timestamped-data": [".tsd"],
    "application/toml": [".toml"],
    "application/trig": [".trig"],
    "application/vnd.3gpp.pic-bw-large": [".plb"],
    "application/vnd.3gpp.pic-bw-small": [".psb"],
    "application/vnd.3gpp.pic-bw-var": [".pvb"],
    "application/vnd.3gpp2.tcap": [".tcap"],
    "application/vnd.3m.post-it-notes": [".pwn"],
    "application/vnd.accpac.simply.aso": [".aso"],
    "application/vnd.accpac.simply.imp": [".imp"],
    "application/vnd.acucobol": [".acu"],
    "application/vnd.acucorp": [".atc", ".acutc"],
    "application/vnd.adobe.air-application-installer-package+zip": [".air"],
    "application/vnd.adobe.flash.movie": [".spl", ".swf"],
    "application/vnd.adobe.formscentral.fcdt": [".fcdt"],
    "application/vnd.adobe.fxp": [".fxp", ".fxpl"],
    "application/vnd.adobe.xdp+xml": [".xdp"],
    "application/vnd.adobe.xfdf": [".xfdf"],
    "application/vnd.ahead.space": [".ahead"],
    "application/vnd.airzip.filesecure.azf": [".azf"],
    "application/vnd.airzip.filesecure.azs": [".azs"],
    "application/vnd.amazon.ebook": [".azw"],
    "application/vnd.amazon.mobi8-ebook": [".azw3", ".kfx"],
    "application/vnd.americandynamics.acc": [".acc"],
    "application/vnd.amiga.ami": [".ami"],
    "application/vnd.android.package-archive": [".apk"],
    "application/vnd.anser-web-certificate-issue-initiation": [".cii"],
    "application/vnd.anser-web-funds-transfer-initiation": [".fti"],
    "application/vnd.antix.game-component": [".atx"],
    "application/vnd.appimage": [".appimage"],
    "application/vnd.apple.installer+xml": [".mpkg"],
    "application/vnd.apple.mpegurl": [".m3u8"],
    "application/vnd.apple.numbers": [".numbers"],
    "application/vnd.apple.pages": [".pages"],
    "application/vnd.apple.pkpass": [".pkpass"],
    "application/vnd.aristanetworks.swi": [".swi"],
    "application/vnd.astraea-software.iota": [".iota"],
    "application/vnd.audiograph": [".aep"],
    "application/vnd.blueice.multipass": [".mpm"],
    "application/vnd.bmi": [".bmi"],
    "application/vnd.businessobjects": [".rep"],
    "application/vnd.chemdraw+xml": [".cdxml"],
    "application/vnd.chess-pgn": [".pgn"],
    "application/vnd.chipnuts.karaoke-mmd": [".mmd"],
    "application/vnd.cinderella": [".cdy"],
    "application/vnd.claymore": [".cla"],
    "application/vnd.cloanto.rp9": [".rp9"],
    "application/vnd.clonk.c4group": [".c4g", ".c4d", ".c4f", ".c4p", ".c4u"],
    "application/vnd.cluetrust.cartomobile-config": [".c11amc"],
    "application/vnd.cluetrust.cartomobile-config-pkg": [".c11amz"],
    "application/vnd.coffeescript": [".coffee"],
    "application/vnd.comicbook+zip": [".cbz"],
    "application/vnd.comicbook-rar": [".cbr"],
    "application/vnd.commonspace": [".csp"],
    "application/vnd.contact.cmsg": [".cdbcmsg"],
    "application/vnd.corel-draw": [".cdr"],
    "application/vnd.cosmocaller": [".cmc"],
    "application/vnd.crick.clicker": [".clkx"],
    "application/vnd.crick.clicker.keyboard": [".clkk"],
    "application/vnd.crick.clicker.palette": [".clkp"],
    "application/vnd.crick.clicker.template": [".clkt"],
    "application/vnd.crick.clicker.wordbank": [".clkw"],
    "application/vnd.criticaltools.wbs+xml": [".wbs"],
    "application/vnd.ctc-posml": [".pml"],
    "application/vnd.cups-ppd": [".ppd"],
    "application/vnd.curl.car": [".car"],
    "application/vnd.curl.pcurl": [".pcurl"],
    "application/vnd.dart": [".dart"],
    "application/vnd.data-vision.rdz": [".rdz"],
    "application/vnd.dbf": [".dbf"],
    "application/vnd.debian.binary-package": [".deb", ".udeb"],
    "application/vnd.dece.data": [".uvf", ".uvvf", ".uvd", ".uvvd"],
    "application/vnd.dece.ttml+xml": [".uvt", ".uvvt"],
    "application/vnd.dece.unspecified": [".uvx", ".uvvx"],
    "application/vnd.dece.zip": [".uvz", ".uvvz"],
    "application/vnd.denovo.fcselayout-link": [".fe_launch"],
    "application/vnd.dna": [".dna"],
    "application/vnd.dolby.mlp": [".mlp"],
    "application/vnd.dpgraph": [".dpg"],
    "application/vnd.dreamfactory": [".dfac"],
    "application/vnd.ds-keypoint": [".kpxx"],
    "application/vnd.dvb.ait": [".ait"],
    "application/vnd.dvb.service": [".svc"],
    "application/vnd.dynageo": [".geo"],
    "application/vnd.ecowin.chart": [".mag"],
    "application/vnd.efi.img": [".img", ".raw-disk-image"],
    "application/vnd.efi.iso": [".iso", ".iso9660"],
    "application/vnd.emusic-emusic_package": [".emp"],
    "application/vnd.enliven": [".nml"],
    "application/vnd.epson.esf": [".esf"],
    "application/vnd.epson.msf": [".msf"],
    "application/vnd.epson.quickanime": [".qam"],
    "application/vnd.epson.salt": [".slt"],
    "application/vnd.epson.ssf": [".ssf"],
    "application/vnd.eszigno3+xml": [".es3", ".et3"],
    "application/vnd.ezpix-album": [".ez2"],
    "application/vnd.ezpix-package": [".ez3"],
    "application/vnd.fdf": [".fdf"],
    "application/vnd.fdsn.mseed": [".mseed"],
    "application/vnd.fdsn.seed": [".seed", ".dataless"],
    "application/vnd.flatpak": [".flatpak", ".xdgapp"],
    "application/vnd.flatpak.ref": [".flatpakref"],
    "application/vnd.flatpak.repo": [".flatpakrepo"],
    "application/vnd.flographit": [".gph"],
    "application/vnd.fluxtime.clip": [".ftc"],
    "application/vnd.framemaker": [".fm", ".frame", ".maker", ".book"],
    "application/vnd.frogans.fnc": [".fnc"],
    "application/vnd.frogans.ltf": [".ltf"],
    "application/vnd.fsc.weblaunch": [".fsc"],
    "application/vnd.fujitsu.oasys": [".oas"],
    "application/vnd.fujitsu.oasys2": [".oa2"],
    "application/vnd.fujitsu.oasys3": [".oa3"],
    "application/vnd.fujitsu.oasysgp": [".fg5"],
    "application/vnd.fujitsu.oasysprs": [".bh2"],
    "application/vnd.fujixerox.ddd": [".ddd"],
    "application/vnd.fujixerox.docuworks": [".xdw"],
    "application/vnd.fujixerox.docuworks.binder": [".xbd"],
    "application/vnd.fuzzysheet": [".fzs"],
    "application/vnd.genomatix.tuxedo": [".txd"],
    "application/vnd.geogebra.file": [".ggb"],
    "application/vnd.geogebra.tool": [".ggt"],
    "application/vnd.geometry-explorer": [".gex", ".gre"],
    "application/vnd.geonext": [".gxt"],
    "application/vnd.geoplan": [".g2w"],
    "application/vnd.geospace": [".g3w"],
    "application/vnd.gmx": [".gmx"],
    "application/vnd.google-earth.kml+xml": [".kml"],
    "application/vnd.google-earth.kmz": [".kmz"],
    "application/vnd.grafeq": [".gqf", ".gqs"],
    "application/vnd.groove-account": [".gac"],
    "application/vnd.groove-help": [".ghf"],
    "application/vnd.groove-identity-message": [".gim"],
    "application/vnd.groove-injector": [".grv"],
    "application/vnd.groove-tool-message": [".gtm"],
    "application/vnd.groove-tool-template": [".tpl"],
    "application/vnd.groove-vcard": [".vcg"],
    "application/vnd.hal+xml": [".hal"],
    "application/vnd.handheld-entertainment+xml": [".zmm"],
    "application/vnd.hbci": [".hbci"],
    "application/vnd.hhe.lesson-player": [".les"],
    "application/vnd.hp-hpgl": [".hpgl"],
    "application/vnd.hp-hpid": [".hpid"],
    "application/vnd.hp-hps": [".hps"],
    "application/vnd.hp-jlyt": [".jlt"],
    "application/vnd.hp-pcl": [".pcl"],
    "application/vnd.hp-pclxl": [".pclxl"],
    "application/vnd.hydrostatix.sof-data": [".sfd-hdstx"],
    "application/vnd.ibm.minipay": [".mpy"],
    "application/vnd.ibm.modcap": [".afp", ".listafp", ".list3820"],
    "application/vnd.ibm.rights-management": [".irm"],
    "application/vnd.ibm.secure-container": [".sc"],
    "application/vnd.iccprofile": [".icc", ".icm"],
    "application/vnd.igloader": [".igl"],
    "application/vnd.immervision-ivp": [".ivp"],
    "application/vnd.immervision-ivu": [".ivu"],
    "application/vnd.insors.igm": [".igm"],
    "application/vnd.intercon.formnet": [".xpw", ".xpx"],
    "application/vnd.intergeo": [".i2g"],
    "application/vnd.intu.qbo": [".qbo"],
    "application/vnd.intu.qfx": [".qfx"],
    "application/vnd.ipunplugged.rcprofile": [".rcprofile"],
    "application/vnd.irepository.package+xml": [".irp"],
    "application/vnd.is-xpr": [".xpr"],
    "application/vnd.isac.fcs": [".fcs"],
    "application/vnd.jam": [".jam"],
    "application/vnd.jcp.javame.midlet-rms": [".rms"],
    "application/vnd.jisp": [".jisp"],
    "application/vnd.joost.joda-archive": [".joda"],
    "application/vnd.kahootz": [".ktz", ".ktr"],
    "application/vnd.kde.karbon": [".karbon"],
    "application/vnd.kde.kchart": [".chrt"],
    "application/vnd.kde.kformula": [".kfo"],
    "application/vnd.kde.kivio": [".flw"],
    "application/vnd.kde.kontour": [".kon"],
    "application/vnd.kde.kpresenter": [".kpr", ".kpt"],
    "application/vnd.kde.kspread": [".ksp"],
    "application/vnd.kde.kword": [".kwd", ".kwt"],
    "application/vnd.kenameaapp": [".htke"],
    "application/vnd.kidspiration": [".kia"],
    "application/vnd.kinar": [".kne", ".knp"],
    "application/vnd.koan": [".skp", ".skd", ".skt", ".skm"],
    "application/vnd.kodak-descriptor": [".sse"],
    "application/vnd.las.las+xml": [".lasxml"],
    "application/vnd.llamagraphics.life-balance.desktop": [".lbd"],
    "application/vnd.llamagraphics.life-balance.exchange+xml": [".lbe"],
    "application/vnd.lotus-1-2-3": [".123", ".wk1", ".wk3", ".wk4"],
    "application/vnd.lotus-approach": [".apr"],
    "application/vnd.lotus-freelance": [".pre"],
    "application/vnd.lotus-notes": [".nsf"],
    "application/vnd.lotus-organizer": [".org"],
    "application/vnd.lotus-screencam": [".scm"],
    "application/vnd.lotus-wordpro": [".lwp"],
    "application/vnd.macports.portpkg": [".portpkg"],
    "application/vnd.mcd": [".mcd"],
    "application/vnd.medcalcdata": [".mc1"],
    "application/vnd.mediastation.cdkey": [".cdkey"],
    "application/vnd.mfer": [".mwf"],
    "application/vnd.mfmp": [".mfm"],
    "application/vnd.micrografx.flo": [".flo"],
    "application/vnd.micrografx.igx": [".igx"],
    "application/vnd.microsoft.portable-executable": [
        ".cpl",
        ".dll",
        ".drv",
        ".efi",
        ".exe",
        ".lib",
        ".ocx",
        ".scr",
        ".sys",
    ],
    "application/vnd.microsoft.windows.thumbnail-cache": [
        ".ehthumbs_vista.db",
        ".image.db",
        ".tvthumb.db",
        ".video.db",
        ".musicthumbs.db",
        ".thumbs.db",
        ".ehthumbs.db",
    ],
    "application/vnd.mif": [".mif"],
    "application/vnd.mobius.daf": [".daf"],
    "application/vnd.mobius.dis": [".dis"],
    "application/vnd.mobius.mbk": [".mbk"],
    "application/vnd.mobius.mqy": [".mqy"],
    "application/vnd.mobius.msl": [".msl"],
    "application/vnd.mobius.plc": [".plc"],
    "application/vnd.mobius.txf": [".txf"],
    "application/vnd.mophun.application": [".mpn"],
    "application/vnd.mophun.certificate": [".mpc"],
    "application/vnd.mozilla.xul+xml": [".xul"],
    "application/vnd.ms-access": [".mdb"],
    "application/vnd.ms-artgalry": [".cil"],
    "application/vnd.ms-asf": [".asf"],
    "application/vnd.ms-cab-compressed": [".cab"],
    "application/vnd.ms-excel": [
        ".xls",
        ".xlm",
        ".xla",
        ".xlc",
        ".xlt",
        ".xlw",
        ".xld",
        ".xll",
    ],
    "application/vnd.ms-excel.addin.macroEnabled.12": [".xlam"],
    "application/vnd.ms-excel.sheet.binary.macroEnabled.12": [".xlsb"],
    "application/vnd.ms-excel.sheet.macroEnabled.12": [".xlsm"],
    "application/vnd.ms-excel.template.macroEnabled.12": [".xltm"],
    "application/vnd.ms-htmlhelp": [".chm"],
    "application/vnd.ms-ims": [".ims"],
    "application/vnd.ms-lrm": [".lrm"],
    "application/vnd.ms-officetheme": [".thmx"],
    "application/vnd.ms-pki.seccat": [".cat"],
    "application/vnd.ms-pki.stl": [".stl"],
    "application/vnd.ms-powerpoint": [".ppt", ".pps", ".pot", ".ppz"],
    "application/vnd.ms-powerpoint.addin.macroEnabled.12": [".ppam"],
    "application/vnd.ms-powerpoint.presentation.macroEnabled.12": [".pptm"],
    "application/vnd.ms-powerpoint.slide.macroEnabled.12": [".sldm"],
    "application/vnd.ms-powerpoint.slideshow.macroEnabled.12": [".ppsm"],
    "application/vnd.ms-powerpoint.template.macroEnabled.12": [".potm"],
    "application/vnd.ms-project": [".mpp", ".mpt"],
    "application/vnd.ms-publisher": [".pub"],
    "application/vnd.ms-tnef": [".tnef", ".tnf"],
    "application/vnd.ms-visio.drawing.macroEnabled.main+xml": [".vsdm"],
    "application/vnd.ms-visio.drawing.main+xml": [".vsdx"],
    "application/vnd.ms-visio.stencil.macroEnabled.main+xml": [".vssm"],
    "application/vnd.ms-visio.stencil.main+xml": [".vssx"],
    "application/vnd.ms-visio.template.macroEnabled.main+xml": [".vstm"],
    "application/vnd.ms-visio.template.main+xml": [".vstx"],
    "application/vnd.ms-word.document.macroEnabled.12": [".docm"],
    "application/vnd.ms-word.template.macroEnabled.12": [".dotm"],
    "application/vnd.ms-works": [".wps", ".wks", ".wcm", ".wdb", ".xlr"],
    "application/vnd.ms-wpl": [".wpl"],
    "application/vnd.ms-xpsdocument": [".xps"],
    "application/vnd.mseq": [".mseq"],
    "application/vnd.musician": [".mus"],
    "application/vnd.muvee.style": [".msty"],
    "application/vnd.mynfc": [".taglet"],
    "application/vnd.neurolanguage.nlu": [".nlu"],
    "application/vnd.nintendo.snes.rom": [".sfc", ".smc"],
    "application/vnd.nitf": [".ntf", ".nitf"],
    "application/vnd.noblenet-directory": [".nnd"],
    "application/vnd.noblenet-sealer": [".nns"],
    "application/vnd.noblenet-web": [".nnw"],
    "application/vnd.nokia.n-gage.data": [".ngdat"],
    "application/vnd.nokia.n-gage.symbian.install": [".n-gage"],
    "application/vnd.nokia.radio-preset": [".rpst"],
    "application/vnd.nokia.radio-presets": [".rpss"],
    "application/vnd.novadigm.edm": [".edm"],
    "application/vnd.novadigm.edx": [".edx"],
    "application/vnd.novadigm.ext": [".ext"],
    "application/vnd.oasis.opendocument.chart": [".odc"],
    "application/vnd.oasis.opendocument.chart-template": [".otc"],
    "application/vnd.oasis.opendocument.database": [".odb"],
    "application/vnd.oasis.opendocument.formula": [".odf"],
    "application/vnd.oasis.opendocument.formula-template": [".odft"],
    "application/vnd.oasis.opendocument.graphics": [".odg"],
    "application/vnd.oasis.opendocument.graphics-flat-xml": [".fodg"],
    "application/vnd.oasis.opendocument.graphics-template": [".otg"],
    "application/vnd.oasis.opendocument.image": [".odi"],
    "application/vnd.oasis.opendocument.image-template": [".oti"],
    "application/vnd.oasis.opendocument.presentation": [".odp"],
    "application/vnd.oasis.opendocument.presentation-flat-xml": [".fodp"],
    "application/vnd.oasis.opendocument.presentation-template": [".otp"],
    "application/vnd.oasis.opendocument.spreadsheet": [".ods"],
    "application/vnd.oasis.opendocument.spreadsheet-flat-xml": [".fods"],
    "application/vnd.oasis.opendocument.spreadsheet-template": [".ots"],
    "application/vnd.oasis.opendocument.text": [".odt"],
    "application/vnd.oasis.opendocument.text-flat-xml": [".fodt"],
    "application/vnd.oasis.opendocument.text-master": [".odm"],
    "application/vnd.oasis.opendocument.text-template": [".ott"],
    "application/vnd.oasis.opendocument.text-web": [".oth"],
    "application/vnd.olpc-sugar": [".xo"],
    "application/vnd.oma.dd2+xml": [".dd2"],
    "application/vnd.oma.drm.content": [".dm", ".dcf"],
    "application/vnd.openofficeorg.extension": [".oxt"],
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": [".pptx"],
    "application/vnd.openxmlformats-officedocument.presentationml.slide": [".sldx"],
    "application/vnd.openxmlformats-officedocument.presentationml.slideshow": [".ppsx"],
    "application/vnd.openxmlformats-officedocument.presentationml.template": [".potx"],
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [".xlsx"],
    "application/vnd.openxmlformats-officedocument.spreadsheetml.template": [".xltx"],
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": [".docx"],
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template": [".dotx"],
    "application/vnd.osgeo.mapguide.package": [".mgp"],
    "application/vnd.osgi.dp": [".dp"],
    "application/vnd.osgi.subsystem": [".esa"],
    "application/vnd.palm": [".pdb", ".pqa", ".oprc"],
    "application/vnd.pawaafile": [".paw"],
    "application/vnd.pg.format": [".str"],
    "application/vnd.pg.osasli": [".ei6"],
    "application/vnd.picsel": [".efif"],
    "application/vnd.pmi.widget": [".wg"],
    "application/vnd.pocketlearn": [".plf"],
    "application/vnd.powerbuilder6": [".pbd"],
    "application/vnd.previewsystems.box": [".box"],
    "application/vnd.proteus.magazine": [".mgz"],
    "application/vnd.publishare-delta-tree": [".qps"],
    "application/vnd.pvi.ptid1": [".ptid"],
    "application/vnd.quark.quarkxpress": [
        ".qxd",
        ".qxt",
        ".qwd",
        ".qwt",
        ".qxl",
        ".qxb",
    ],
    "application/vnd.rar": [".rar"],
    "application/vnd.realvnc.bed": [".bed"],
    "application/vnd.recordare.musicxml": [".mxl"],
    "application/vnd.recordare.musicxml+xml": [".musicxml"],
    "application/vnd.rig.cryptonote": [".cryptonote"],
    "application/vnd.rim.cod": [".cod"],
    "application/vnd.rn-realmedia": [".rm", ".rmj", ".rmx", ".rmm"],
    "application/vnd.rn-realmedia-vbr": [".rmvb"],
    "application/vnd.route66.link66+xml": [".link66"],
    "application/vnd.sailingtracker.track": [".st"],
    "application/vnd.seemail": [".see"],
    "application/vnd.sema": [".sema"],
    "application/vnd.semd": [".semd"],
    "application/vnd.semf": [".semf"],
    "application/vnd.shana.informed.formdata": [".ifm"],
    "application/vnd.shana.informed.formtemplate": [".itp"],
    "application/vnd.shana.informed.interchange": [".iif"],
    "application/vnd.shana.informed.package": [".ipk"],
    "application/vnd.simtech-mindmapper": [".twd", ".twds"],
    "application/vnd.smaf": [".mmf", ".smaf"],
    "application/vnd.smart.teacher": [".teacher"],
    "application/vnd.snap": [".snap"],
    "application/vnd.solent.sdkm+xml": [".sdkm", ".sdkd"],
    "application/vnd.spotfire.dxp": [".dxp"],
    "application/vnd.spotfire.sfs": [".sfs"],
    "application/vnd.sqlite3": [".sqlite3"],
    "application/vnd.squashfs": [".sqsh"],
    "application/vnd.stardivision.calc": [".sdc"],
    "application/vnd.stardivision.chart": [".sds"],
    "application/vnd.stardivision.draw": [".sda"],
    "application/vnd.stardivision.impress": [".sdd"],
    "application/vnd.stardivision.mail": [".smd"],
    "application/vnd.stardivision.math": [".smf"],
    "application/vnd.stardivision.writer": [".sdw", ".vor"],
    "application/vnd.stardivision.writer-global": [".sgl"],
    "application/vnd.stepmania.package": [".smzip"],
    "application/vnd.stepmania.stepchart": [".sm"],
    "application/vnd.sun.xml.calc": [".sxc"],
    "application/vnd.sun.xml.calc.template": [".stc"],
    "application/vnd.sun.xml.draw": [".sxd"],
    "application/vnd.sun.xml.draw.template": [".std"],
    "application/vnd.sun.xml.impress": [".sxi"],
    "application/vnd.sun.xml.impress.template": [".sti"],
    "application/vnd.sun.xml.math": [".sxm"],
    "application/vnd.sun.xml.writer": [".sxw"],
    "application/vnd.sun.xml.writer.global": [".sxg"],
    "application/vnd.sun.xml.writer.template": [".stw"],
    "application/vnd.sus-calendar": [".sus", ".susp"],
    "application/vnd.svd": [".svd"],
    "application/vnd.symbian.install": [".sis", ".sisx"],
    "application/vnd.syncml+xml": [".xsm"],
    "application/vnd.syncml.dm+wbxml": [".bdm"],
    "application/vnd.syncml.dm+xml": [".xdm"],
    "application/vnd.tao.intent-module-archive": [".tao"],
    "application/vnd.tcpdump.pcap": [".pcap", ".cap", ".dmp"],
    "application/vnd.tmobile-livetv": [".tmo"],
    "application/vnd.trid.tpt": [".tpt"],
    "application/vnd.triscape.mxs": [".mxs"],
    "application/vnd.trueapp": [".tra"],
    "application/vnd.ufdl": [".ufd", ".ufdl"],
    "application/vnd.uiq.theme": [".utz"],
    "application/vnd.umajin": [".umj"],
    "application/vnd.unity": [".unityweb"],
    "application/vnd.uoml+xml": [".uoml"],
    "application/vnd.vcx": [".vcx"],
    "application/vnd.visio": [".vsd", ".vst", ".vss", ".vsw"],
    "application/vnd.visionary": [".vis"],
    "application/vnd.vsf": [".vsf"],
    "application/vnd.wap.wbxml": [".wbxml"],
    "application/vnd.wap.wmlc": [".wmlc"],
    "application/vnd.wap.wmlscriptc": [".wmlsc"],
    "application/vnd.webturbo": [".wtb"],
    "application/vnd.wolfram.player": [".nbp"],
    "application/vnd.wordperfect": [".wpd", ".wpp", ".wp6", ".wp", ".wp5", ".wp4"],
    "application/vnd.wqd": [".wqd"],
    "application/vnd.wt.stf": [".stf"],
    "application/vnd.xara": [".xar"],
    "application/vnd.xfdl": [".xfdl"],
    "application/vnd.yamaha.hv-dic": [".hvd"],
    "application/vnd.yamaha.hv-script": [".hvs"],
    "application/vnd.yamaha.hv-voice": [".hvp"],
    "application/vnd.yamaha.openscoreformat": [".osf"],
    "application/vnd.yamaha.openscoreformat.osfpvg+xml": [".osfpvg"],
    "application/vnd.yamaha.smaf-audio": [".saf"],
    "application/vnd.yamaha.smaf-phrase": [".spf"],
    "application/vnd.yellowriver-custom-menu": [".cmp"],
    "application/vnd.zul": [".zir", ".zirz"],
    "application/vnd.zzazz.deck+xml": [".zaz"],
    "application/voicexml+xml": [".vxml"],
    "application/wasm": [".wasm"],
    "application/widget": [".wgt"],
    "application/winhlp": [".hlp"],
    "application/wsdl+xml": [".wsdl"],
    "application/wspolicy+xml": [".wspolicy"],
    "application/x-7z-compressed": [".7z", ".7z.001"],
    "application/x-abiword": [".abw", ".abw.gz", ".zabw", ".abw.crashed"],
    "application/x-ace": [".ace"],
    "application/x-alz": [".alz"],
    "application/x-amiga-disk-format": [".adf"],
    "application/x-amipro": [".sam"],
    "application/x-aportisdoc": [".pdc"],
    "application/x-apple-diskimage": [".dmg"],
    "application/x-apple-systemprofiler+xml": [".spx"],
    "application/x-appleworks-document": [".cwk"],
    "application/x-applix-spreadsheet": [".as"],
    "application/x-archive": [".a", ".ar"],
    "application/x-arj": [".arj"],
    "application/x-asar": [".asar"],
    "application/x-asp": [".asp"],
    "application/x-atari-2600-rom": [".a26"],
    "application/x-atari-7800-rom": [".a78"],
    "application/x-atari-lynx-rom": [".lnx"],
    "application/x-authorware-bin": [".aab", ".x32", ".u32", ".vox"],
    "application/x-authorware-map": [".aam"],
    "application/x-authorware-seg": [".aas"],
    "application/x-awk": [".awk"],
    "application/x-bat": [".bat"],
    "application/x-bcpio": [".bcpio"],
    "application/x-bittorrent": [".torrent"],
    "application/x-blender": [".BLEND", ".blend", ".blender"],
    "application/x-blorb": [".blb", ".blorb"],
    "application/x-bps-patch": [".bps"],
    "application/x-bsdiff": [".bsdiff"],
    "application/x-bzdvi": [".dvi.bz2"],
    "application/x-bzip": [".bz"],
    "application/x-bzip1-compressed-tar": [".tar.bz", ".tbz"],
    "application/x-bzip2": [".bz2", ".boz"],
    "application/x-bzip2-compressed-tar": [".tar.bz2", ".tb2", ".tbz2"],
    "application/x-bzip3": [".bz3"],
    "application/x-bzip3-compressed-tar": [".tar.bz3", ".tbz3"],
    "application/x-bzpdf": [".pdf.bz2"],
    "application/x-bzpostscript": [".ps.bz2"],
    "application/x-cb7": [".cb7"],
    "application/x-cbr": [".cba", ".cbt"],
    "application/x-ccmx": [".ccmx"],
    "application/x-cdlink": [".vcd"],
    "application/x-cdrdao-toc": [".toc"],
    "application/x-cfs-compressed": [".cfs"],
    "application/x-chat": [".chat"],
    "application/x-cisco-vpn-settings": [".pcf"],
    "application/x-compress": [".Z", ".z"],
    "application/x-compressed-iso": [".cso"],
    "application/x-compressed-tar": [".tar.gz", ".tgz"],
    "application/x-conference": [".nsc"],
    "application/x-core": [".core", ".core:cs"],
    "application/x-cpio": [".cpio"],
    "application/x-cpio-compressed": [".cpio.gz"],
    "application/x-csh": [".csh"],
    "application/x-cue": [".cue"],
    "application/x-dar": [".dar"],
    "application/x-designer": [".ui"],
    "application/x-desktop": [".desktop", ".kdelnk"],
    "application/x-dgc-compressed": [".dgc"],
    "application/x-dia-diagram": [".dia"],
    "application/x-dia-shape": [".shape"],
    "application/x-director": [
        ".dir",
        ".dcr",
        ".dxr",
        ".cst",
        ".cct",
        ".cxt",
        ".w3d",
        ".fgd",
        ".swa",
    ],
    "application/x-discjuggler-cd-image": [".cdi"],
    "application/x-docbook+xml": [".docbook"],
    "application/x-doom": [".wad"],
    "application/x-dtbncx+xml": [".ncx"],
    "application/x-dtbook+xml": [".dtb"],
    "application/x-dtbresource+xml": [".res"],
    "application/x-dvi": [".dvi"],
    "application/x-e-theme": [".etheme"],
    "application/x-egon": [".egon"],
    "application/x-envoy": [".evy"],
    "application/x-eris-link+cbor": [".eris"],
    "application/x-eva": [".eva"],
    "application/x-excellon": [".drl"],
    "application/x-fds-disk": [".fds"],
    "application/x-fictionbook+xml": [".fb2"],
    "application/x-fishscript": [".fish"],
    "application/x-fluid": [".fl"],
    "application/x-font-afm": [".afm"],
    "application/x-font-bdf": [".bdf"],
    "application/x-font-ghostscript": [".gsf"],
    "application/x-font-linux-psf": [".psf"],
    "application/x-font-pcf": [".pcf.z", ".pcf.gz"],
    "application/x-font-snf": [".snf"],
    "application/x-font-speedo": [".spd"],
    "application/x-font-ttf": [".ttc"],
    "application/x-font-ttx": [".ttx"],
    "application/x-font-type1": [".pfa", ".pfb", ".pfm"],
    "application/x-freearc": [".arc"],
    "application/x-gameboy-color-rom": [".cgb", ".gbc"],
    "application/x-gameboy-rom": [".gb", ".sgb"],
    "application/x-gamegear-rom": [".gg"],
    "application/x-gba-rom": [".agb", ".gba"],
    "application/x-gca-compressed": [".gca"],
    "application/x-gd-rom-cue": [".gdi"],
    "application/x-gdscript": [".gd"],
    "application/x-genesis-32x-rom": [".32x", ".mdx"],
    "application/x-genesis-rom": [".gen", ".sgd"],
    "application/x-gerber-job": [".gbrjob"],
    "application/x-gettext-translation": [".gmo", ".mo"],
    "application/x-glade": [".glade"],
    "application/x-glulx": [".ulx"],
    "application/x-gnucash": [".gnc", ".gnucash", ".xac"],
    "application/x-gnumeric": [".gnumeric"],
    "application/x-gnuplot": [".gnuplot", ".gp", ".gplt"],
    "application/x-go-sgf": [".sgf"],
    "application/x-godot-project": [".project.godot"],
    "application/x-godot-resource": [".tres"],
    "application/x-godot-scene": [".escn", ".scn", ".tscn"],
    "application/x-godot-shader": [".gdshader"],
    "application/x-gramps-xml": [".gramps"],
    "application/x-graphite": [".gra"],
    "application/x-gtar": [".gtar"],
    "application/x-gz-font-linux-psf": [".psf.gz"],
    "application/x-gzdvi": [".dvi.gz"],
    "application/x-gzpdf": [".pdf.gz"],
    "application/x-gzpostscript": [".ps.gz"],
    "application/x-hdf": [".hdf", ".hdf5", ".h4", ".hdf4"],
    "application/x-hdf5": [".h5"],
    "application/x-hfe-floppy-image": [".hfe"],
    "application/x-hwp": [".hwp"],
    "application/x-hwt": [".hwt"],
    "application/x-ica": [".ica"],
    "application/x-install-instructions": [".install"],
    "application/x-ips-patch": [".ips"],
    "application/x-ipynb+json": [".ipynb"],
    "application/x-it87": [".it87"],
    "application/x-java": [".java"],
    "application/x-java-jce-keystore": [".jceks"],
    "application/x-java-jnlp-file": [".jnlp"],
    "application/x-java-keystore": [".jks", ".ks"],
    "application/x-java-pack200": [".pack"],
    "application/x-jbuilder-project": [".jpr", ".jpx"],
    "application/x-kexi-connectiondata": [".kexic"],
    "application/x-kexiproject-shortcut": [".kexis"],
    "application/x-kexiproject-sqlite2": [".kexi"],
    "application/x-killustrator": [".kil"],
    "application/x-kpovmodeler": [".kpm"],
    "application/x-krita": [".kra", ".krz"],
    "application/x-kugar": [".kud"],
    "application/x-latex": [".latex"],
    "application/x-lha": [".lha", ".lzh"],
    "application/x-lhz": [".lhz"],
    "application/x-lmdb": [".lmdb"],
    "application/x-lrzip": [".lrz"],
    "application/x-lrzip-compressed-tar": [".tar.lrz", ".tlrz"],
    "application/x-lyx": [".lyx"],
    "application/x-lz4": [".lz4"],
    "application/x-lz4-compressed-tar": [".tar.lz4"],
    "application/x-lzip": [".lz"],
    "application/x-lzip-compressed-tar": [".tar.lz"],
    "application/x-lzma": [".lzma"],
    "application/x-lzma-compressed-tar": [".tar.lzma", ".tlz"],
    "application/x-lzop": [".lzo"],
    "application/x-lzpdf": [".pdf.lz"],
    "application/x-m4": [".m4"],
    "application/x-mame-chd": [".chd"],
    "application/x-markaby": [".mab"],
    "application/x-mie": [".mie"],
    "application/x-mimearchive": [".mht", ".mhtml"],
    "application/x-mobipocket-ebook": [".prc", ".mobi"],
    "application/x-modrinth-modpack+zip": [".mrpack"],
    "application/x-mpegurl": [".m3u"],
    "application/x-ms-application": [".application"],
    "application/x-ms-shortcut": [".lnk"],
    "application/x-ms-wim": [".swm", ".wim"],
    "application/x-ms-wmd": [".wmd"],
    "application/x-ms-wmz": [".wmz"],
    "application/x-ms-xbap": [".xbap"],
    "application/x-msbinder": [".obd"],
    "application/x-mscardfile": [".crd"],
    "application/x-msclip": [".clp"],
    "application/x-msdownload": [".com", ".msi"],
    "application/x-msmediaview": [".mvb", ".m13", ".m14"],
    "application/x-msmetafile": [".wmf", ".emf", ".emz"],
    "application/x-msmoney": [".mny"],
    "application/x-msschedule": [".scd"],
    "application/x-msterminal": [".trm"],
    "application/x-mswinurl": [".url"],
    "application/x-mswrite": [".wri"],
    "application/x-msx-rom": [".msx"],
    "application/x-n64-rom": [".n64", ".v64", ".z64"],
    "application/x-navi-animation": [".ani"],
    "application/x-neo-geo-pocket-color-rom": [".ngc"],
    "application/x-neo-geo-pocket-rom": [".ngp"],
    "application/x-nes-rom": [".nes", ".nez", ".unf", ".unif"],
    "application/x-netcdf": [".nc", ".cdf"],
    "application/x-nintendo-3ds-executable": [".3dsx"],
    "application/x-nintendo-3ds-rom": [".3ds", ".cci"],
    "application/x-nintendo-ds-rom": [".nds"],
    "application/x-nuscript": [".nu"],
    "application/x-nzb": [".nzb"],
    "application/x-object": [".mod", ".o"],
    "application/x-oleo": [".oleo"],
    "application/x-openvpn-profile": [".openvpn", ".ovpn"],
    "application/x-openzim": [".zim"],
    "application/x-pagemaker": [".p65", ".pm", ".pm6", ".pmd"],
    "application/x-pak": [".pak"],
    "application/x-par2": [".PAR2", ".par2"],
    "application/x-partial-download": [".crdownload", ".part", ".wkdownload"],
    "application/x-pc-engine-rom": [".pce"],
    "application/x-perf-data": [".perf.data:cs", ".perf.data"],
    "application/x-perl": [".PL", ".al", ".perl", ".pl", ".pod", ".t"],
    "application/x-php": [".php", ".php3", ".php4", ".php5", ".phps"],
    "application/x-pkcs7-certificates": [".p7b", ".spc"],
    "application/x-pkcs7-certreqresp": [".p7r"],
    "application/x-planperfect": [".pln"],
    "application/x-pocket-word": [".psw"],
    "application/x-powershell": [".ps1"],
    "application/x-profile": [".gmon.out"],
    "application/x-pw": [".pw"],
    "application/x-pyspread-bz-spreadsheet": [".pys"],
    "application/x-pyspread-spreadsheet": [".pysu"],
    "application/x-python-bytecode": [".pyc", ".pyo"],
    "application/x-python-code": [".py"],
    "application/x-qed-disk": [".qed"],
    "application/x-qemu-disk": [".qcow", ".qcow2"],
    "application/x-qpress": [".qp"],
    "application/x-qtiplot": [".qti", ".qti.gz"],
    "application/x-quattropro": [".wb1", ".wb2", ".wb3"],
    "application/x-quicktime-media-link": [".qtl"],
    "application/x-qw": [".qif"],
    "application/x-rar-compressed": [".rar"],
    "application/x-raw-disk-image-xz-compressed": [".img.xz", ".raw-disk-image.xz"],
    "application/x-raw-floppy-disk-image": [".fd", ".qd"],
    "application/x-research-info-systems": [".ris"],
    "application/x-rpm": [".rpm"],
    "application/x-ruby": [".rb"],
    "application/x-sami": [".sami"],
    "application/x-sg1000-rom": [".sg"],
    "application/x-sh": [".sh"],
    "application/x-shar": [".shar"],
    "application/x-shared-library-la": [".la"],
    "application/x-sharedlib": [".so"],
    "application/x-shellscript": [".sh"],
    "application/x-shorten": [".shn"],
    "application/x-siag": [".siag"],
    "application/x-silverlight-app": [".xap"],
    "application/x-sms-rom": [".sms"],
    "application/x-source-rpm": [".spm", ".src.rpm"],
    "application/x-spss-por": [".por"],
    "application/x-spss-sav": [".sav", ".zsav"],
    "application/x-sql": [".sql"],
    "application/x-sqlite2": [".sqlite2"],
    "application/x-stuffit": [".sit"],
    "application/x-stuffitx": [".sitx"],
    "application/x-subrip": [".srt"],
    "application/x-sv4cpio": [".sv4cpio"],
    "application/x-sv4crc": [".sv4crc"],
    "application/x-t3vm-image": [".t3"],
    "application/x-t602": [".602"],
    "application/x-tads": [".gam"],
    "application/x-tar": [".tar", ".gem"],
    "application/x-tarz": [".tar.Z", ".taz", ".tar.z"],
    "application/x-tcl": [".tcl"],
    "application/x-tex": [".tex"],
    "application/x-tex-gf": [".gf"],
    "application/x-tex-pk": [".pk"],
    "application/x-tex-tfm": [".tfm"],
    "application/x-texinfo": [".texinfo", ".texi"],
    "application/x-tgif": [".obj"],
    "application/x-theme": [".theme"],
    "application/x-thomson-cartridge-memo7": [".m7"],
    "application/x-thomson-cassette": [".k7"],
    "application/x-thomson-sap-image": [".sap"],
    "application/x-tiled-tmx": [".tmx"],
    "application/x-tiled-tsx": [".tsx"],
    "application/x-trash": [".bak", ".old", ".sik"],
    "application/x-troff": [".roff", ".tr"],
    "application/x-troff-man": [".[1-9]", ".man"],
    "application/x-troff-me": [".me"],
    "application/x-troff-ms": [".ms"],
    "application/x-tzo": [".tar.lzo", ".tzo"],
    "application/x-ufraw": [".ufraw"],
    "application/x-ustar": [".ustar"],
    "application/x-vdi-disk": [".vdi"],
    "application/x-vhd-disk": [".vhd", ".vpc"],
    "application/x-vhdx-disk": [".vhdx"],
    "application/x-virtual-boy-rom": [".vb"],
    "application/x-vmdk-disk": [".vmdk"],
    "application/x-wais-source": [".src"],
    "application/x-windows-themepack": [".themepack"],
    "application/x-wonderswan-color-rom": [".wsc"],
    "application/x-wonderswan-rom": [".ws"],
    "application/x-wpg": [".wpg"],
    "application/x-wwf": [".wwf"],
    "application/x-x509-ca-cert": [".der", ".crt", ".pem", ".cert"],
    "application/x-xar": [".xar"],
    "application/x-xbel": [".xbel"],
    "application/x-xfig": [".fig"],
    "application/x-xliff+xml": [".xlf"],
    "application/x-xpinstall": [".xpi"],
    "application/x-xz": [".xz"],
    "application/x-xz-compressed-tar": [".tar.xz", ".txz"],
    "application/x-xzpdf": [".pdf.xz"],
    "application/x-zip-compressed-fb2": [".fb2.zip"],
    "application/x-zmachine": [".z1", ".z2", ".z3", ".z4", ".z5", ".z6", ".z7", ".z8"],
    "application/x-zoo": [".zoo"],
    "application/x-zpaq": [".zpaq"],
    "application/x-zstd-compressed-tar": [".tar.zst", ".tzst"],
    "application/x.systemd-confext": [".confext.raw"],
    "application/x.systemd-sysext": [".sysext.raw"],
    "application/xaml+xml": [".xaml"],
    "application/xcap-diff+xml": [".xdf"],
    "application/xenc+xml": [".xenc"],
    "application/xhtml+xml": [".xhtml", ".xht"],
    "application/xliff+xml": [".xliff"],
    "application/xml": [".xml", ".xsl", ".rng", ".xsd", ".xpdl", ".xbl"],
    "application/xml-dtd": [".dtd"],
    "application/xml-external-parsed-entity": [".ent"],
    "application/xop+xml": [".xop"],
    "application/xproc+xml": [".xpl"],
    "application/xslt+xml": [".xslt"],
    "application/xspf+xml": [".xspf"],
    "application/xv+xml": [".mxml", ".xhvml", ".xvml", ".xvm"],
    "application/yaml": [".yaml", ".yml"],
    "application/yang": [".yang"],
    "application/yin+xml": [".yin"],
    "application/zip": [".zip", ".zipx"],
    "application/zlib": [".zz"],
    "application/zstd": [".zst"],
    "audio/3gpp": [".3gp", ".3ga", ".3gpp"],
    "audio/3gpp2": [".3g2", ".3gpp2"],
    "audio/AMR": [".amr"],
    "audio/AMR-WB": [".awb"],
    "audio/aac": [".aac", ".adts", ".ass"],
    "audio/ac3": [".ac3"],
    "audio/adpcm": [".adp"],
    "audio/ak3g": [".ak3g"],
    "audio/amr": [".wav"],
    "audio/amr-wb": [".amw"],
    "audio/annodex": [".axa"],
    "audio/basic": [".au", ".snd"],
    "audio/evrc": [".evc"],
    "audio/flac": [".flac"],
    "audio/imelody": [".imy"],
    "audio/isma": [".isma"],
    "audio/kr3g": [".k3g"],
    "audio/m4a": [".m4a"],
    "audio/mid": [".mid", ".midi"],
    "audio/midi": [".kar", ".rmi"],
    "audio/mobile-xmf": [".mxmf"],
    "audio/mp2": [".mp2"],
    "audio/mp4": [".mp4a", ".m4a", ".f4a"],
    "audio/mpeg": [".mpga", ".mp2a", ".mp3", ".m2a", ".m3a"],
    "audio/ogg": [".oga", ".ogg"],
    "audio/opus": [".opus"],
    "audio/prs.sid": [".psid", ".sid"],
    "audio/qcelp": [".qcp"],
    "audio/s3m": [".s3m"],
    "audio/silk": [".sil"],
    "audio/usac": [".loas", ".xhe"],
    "audio/vnd.audible.aax": [".aax"],
    "audio/vnd.audible.aaxc": [".aaxc"],
    "audio/vnd.dece.audio": [".uva", ".uvva"],
    "audio/vnd.digital-winds": [".eol"],
    "audio/vnd.dra": [".dra"],
    "audio/vnd.dts": [".dts"],
    "audio/vnd.dts.hd": [".dtshd"],
    "audio/vnd.lucent.voice": [".lvp"],
    "audio/vnd.ms-playready.media.pya": [".pya"],
    "audio/vnd.nuera.ecelp4800": [".ecelp4800"],
    "audio/vnd.nuera.ecelp7470": [".ecelp7470"],
    "audio/vnd.nuera.ecelp9600": [".ecelp9600"],
    "audio/vnd.rip": [".rip"],
    "audio/vnd.rn-realaudio": [".ra", ".rax"],
    "audio/vnd.wave": [".wav"],
    "audio/webm": [".weba"],
    "audio/x- dff": [".dff"],
    "audio/x-aac": [".aac"],
    "audio/x-aifc": [".aifc", ".aiffc"],
    "audio/x-aiff": [".aif", ".aiff"],
    "audio/x-amzxml": [".amz"],
    "audio/x-ape": [".ape"],
    "audio/x-caf": [".caf"],
    "audio/x-dff": [".dff"],
    "audio/x-dsf": [".dsf"],
    "audio/x-flac": [".flac"],
    "audio/x-gsm": [".gsm"],
    "audio/x-iriver-pla": [".pla"],
    "audio/x-it": [".it"],
    "audio/x-m4b": [".f4b", ".m4b"],
    "audio/x-m4r": [".m4r"],
    "audio/x-matroska": [".mka"],
    "audio/x-minipsf": [".minipsf"],
    "audio/x-mo3": [".mo3"],
    "audio/x-mod": [".669", ".m15", ".med", ".mtm", ".ult", ".uni"],
    "audio/x-mpegurl": [".vlc"],
    "audio/x-ms-asx": [".asx", ".wax", ".wmx", ".wvx"],
    "audio/x-ms-wax": [".wax"],
    "audio/x-ms-wma": [".wma"],
    "audio/x-musepack": [".mp+"],
    "audio/x-pn-audibleaudio": [".aa"],
    "audio/x-pn-realaudio-plugin": [".rmp"],
    "audio/x-psf": [".psf"],
    "audio/x-psflib": [".psflib"],
    "audio/x-s3m": [".s3m"],
    "audio/x-scpls": [".scpls"],
    "audio/x-speex": [".speex"],
    "audio/x-stm": [".stm"],
    "audio/x-tak": [".tak"],
    "audio/x-tta": [".tta"],
    "audio/x-voc": [".voc"],
    "audio/x-wav": [".wav"],
    "audio/x-wavpack": [".wv", ".wvp"],
    "audio/x-wavpack-correction": [".wvc"],
    "audio/x-xi": [".xi"],
    "audio/x-xm": [".xm"],
    "audio/x-xmf": [".xmf"],
    "audio/xm": [".xm"],
    "chemical/x-cdx": [".cdx"],
    "chemical/x-cif": [".cif"],
    "chemical/x-cmdf": [".cmdf"],
    "chemical/x-cml": [".cml"],
    "chemical/x-csml": [".csml"],
    "chemical/x-pdb": [".brk"],
    "chemical/x-xyz": [".xyz"],
    "font/eot": [".eot"],
    "font/open-type": [".otf"],
    "font/otf": [".otf"],
    "font/sfnt": [".ttf"],
    "font/true-type": [".ttf"],
    "font/ttf": [".ttf"],
    "font/woff": [".woff"],
    "font/font-woff": [".woff"],
    "font/x-font-woff": [".woff"],
    "font/font-woff2": [".woff2"],
    "font/x-font-woff2": [".woff2"],
    "font/woff2": [".woff2"],
    "font/x-font-ttf": [".ttf"],
    "font/x-font-woff": [".woff"],
    "image/apng": [".apng", ".png"],
    "image/astc": [".astc"],
    "image/avif": [".avif", ".avifs"],
    "image/bmp": [".bmp", ".dib"],
    "image/cgm": [".cgm"],
    "image/emf": [".emf"],
    "image/g3fax": [".g3"],
    "image/gif": [".gif"],
    "image/heic": [".heic"],
    "image/heif": [".heif", ".hif"],
    "image/ief": [".ief"],
    "image/jp2": [".jp2", ".jpg2"],
    "image/jpeg": [".jpeg", ".jpg", ".jpe", ".jfif"],
    "image/jpg": [".jpg"],
    "image/jpm": [".jpgm", ".jpm"],
    "image/jpx": [".jpf"],
    "image/jxl": [".jxl"],
    "image/jxr": [".hdp", ".jxr", ".wdp"],
    "image/ktx": [".ktx"],
    "image/ktx2": [".ktx2"],
    "image/openraster": [".ora"],
    "image/png": [".png"],
    "image/prs.btif": [".btif"],
    "image/qoi": [".qoi"],
    "image/rle": [".rle"],
    "image/sgi": [".sgi"],
    "image/svg+xml": [".svg", ".svgz"],
    "image/svg+xml-compressed": [".svg.gz"],
    "image/tiff": [".tiff", ".tif"],
    "image/vnd.adobe.photoshop": [".psd"],
    "image/vnd.dece.graphic": [".uvi", ".uvvi", ".uvg", ".uvvg"],
    "image/vnd.djvu": [".djvu", ".djv"],
    "image/vnd.dvb.subtitle": [".sub"],
    "image/vnd.dwg": [".dwg"],
    "image/vnd.dxf": [".dxf"],
    "image/vnd.fastbidsheet": [".fbs"],
    "image/vnd.fpx": [".fpx"],
    "image/vnd.fst": [".fst"],
    "image/vnd.fujixerox.edmics-mmr": [".mmr"],
    "image/vnd.fujixerox.edmics-rlc": [".rlc"],
    "image/vnd.microsoft.icon": [".ico"],
    "image/vnd.ms-modi": [".mdi"],
    "image/vnd.net-fpx": [".npx"],
    "image/vnd.rn-realpix": [".rp"],
    "image/vnd.wap.wbmp": [".wbmp"],
    "image/vnd.xiff": [".xif"],
    "image/vnd.zbrush.pcx": [".pcx"],
    "image/webp": [".webp"],
    "image/wmf": [".wmf"],
    "image/x-3ds": [".3ds"],
    "image/x-adobe-dng": [".dng"],
    "image/x-applix-graphics": [".ag"],
    "image/x-bzeps": [".eps.bz2", ".epsf.bz2", ".epsi.bz2"],
    "image/x-canon-cr2": [".cr2"],
    "image/x-canon-cr3": [".cr3"],
    "image/x-canon-crw": [".crw"],
    "image/x-cmu-raster": [".ras"],
    "image/x-cmx": [".cmx"],
    "image/x-compressed-xcf": [".xcf.bz2", ".xcf.gz"],
    "image/x-dds": [".dds"],
    "image/x-eps": [".epsf", ".epsi"],
    "image/x-exr": [".exr"],
    "image/x-freehand": [".fh", ".fhc", ".fh4", ".fh5", ".fh7"],
    "image/x-fuji-raf": [".raf"],
    "image/x-gimp-gbr": [".gbr"],
    "image/x-gimp-gih": [".gih"],
    "image/x-gimp-pat": [".pat"],
    "image/x-gzeps": [".eps.gz", ".epsf.gz", ".epsi.gz"],
    "image/x-icns": [".icns"],
    "image/x-icon": [".ico"],
    "image/x-ilbm": [".iff", ".ilbm", ".lbm"],
    "image/x-jng": [".jng"],
    "image/x-jp2-codestream": [".j2c", ".j2k", ".jpc"],
    "image/x-kodak-dcr": [".dcr"],
    "image/x-kodak-k25": [".k25"],
    "image/x-kodak-kdc": [".kdc"],
    "image/x-lwo": [".lwo", ".lwob"],
    "image/x-lws": [".lws"],
    "image/x-macpaint": [".pntg"],
    "image/x-minolta-mrw": [".mrw"],
    "image/x-msod": [".msod"],
    "image/x-nikon-nef": [".nef"],
    "image/x-nikon-nrw": [".nrw"],
    "image/x-olympus-orf": [".orf"],
    "image/x-panasonic-rw": [".raw"],
    "image/x-panasonic-rw2": [".rw2"],
    "image/x-pcx": [".pcx"],
    "image/x-pentax-pef": [".pef"],
    "image/x-photo-cd": [".pcd"],
    "image/x-pict": [".pic", ".pct", ".pict", ".pict1", ".pict2"],
    "image/x-portable-anymap": [".pnm"],
    "image/x-portable-bitmap": [".pbm"],
    "image/x-portable-graymap": [".pgm"],
    "image/x-portable-pixmap": [".ppm"],
    "image/x-quicktime": [".qtif"],
    "image/x-rgb": [".rgb"],
    "image/x-sgi": [".sgi"],
    "image/x-sigma-x3f": [".x3f"],
    "image/x-skencil": [".sk", ".sk1"],
    "image/x-sony-arw": [".arw"],
    "image/x-sony-sr2": [".sr2"],
    "image/x-sony-srf": [".srf"],
    "image/x-sun-raster": [".sun"],
    "image/x-tga": [".tga", ".icb", ".vda", ".tpic"],
    "image/x-win-bitmap": [".cur"],
    "image/x-xbitmap": [".xbm"],
    "image/x-xcf": [".xcf"],
    "image/x-xpixmap": [".xpm"],
    "image/x-xwindowdump": [".xwd"],
    "message/rfc822": [".eml", ".mime"],
    "message/x-gnu-rmail": [".rmail"],
    "model/3mf": [".3mf"],
    "model/gltf+json": [".gltf"],
    "model/gltf-binary": [".glb"],
    "model/iges": [".igs", ".iges"],
    "model/mesh": [".msh", ".mesh", ".silo"],
    "model/mtl": [".mtl"],
    "model/obj": [".obj"],
    "model/stl": [".stl"],
    "model/vnd.collada+xml": [".dae"],
    "model/vnd.dwf": [".dwf"],
    "model/vnd.gdl": [".gdl"],
    "model/vnd.gtw": [".gtw"],
    "model/vnd.mts": [".mts"],
    "model/vnd.vtu": [".vtu"],
    "model/vrml": [".wrl", ".vrml", ".vrm"],
    "model/x3d+binary": [".x3db", ".x3dbz"],
    "model/x3d+vrml": [".x3dv", ".x3dvz"],
    "model/x3d+xml": [".x3d", ".x3dz"],
    "text/cache-manifest": [".appcache", ".manifest"],
    "text/calendar": [".ics", ".ifb"],
    "text/css": [".css"],
    "text/csv": [".csv"],
    "text/csv-schema": [".csvs"],
    "text/html": [".html", ".htm"],
    "text/javascript": [".jsm", ".mjs"],
    "text/jscript.encode": [".jse"],
    "text/julia": [".jl"],
    "text/markdown": [".markdown", ".md", ".mkd"],
    "text/n3": [".n3"],
    "text/org": [".org"],
    "text/plain": [".txt", ".text", ".conf", ".def", ".list", ".log", ".in"],
    "text/prs.lines.tag": [".dsc"],
    "text/richtext": [".rtx"],
    "text/rust": [".rs"],
    "text/sgml": [".sgml", ".sgm"],
    "text/spreadsheet": [".slk", ".sylk"],
    "text/tab-separated-values": [".tsv"],
    "text/tcl": [".tk"],
    "text/troff": [".troff"],
    "text/turtle": [".ttl"],
    "text/uri-list": [".uri", ".uris", ".urls"],
    "text/vbscript": [".vbs"],
    "text/vbscript.encode": [".vbe"],
    "text/vcard": [".vcard", ".gcrd", ".vct"],
    "text/vnd.curl": [".curl"],
    "text/vnd.curl.dcurl": [".dcurl"],
    "text/vnd.curl.mcurl": [".mcurl"],
    "text/vnd.curl.scurl": [".scurl"],
    "text/vnd.familysearch.gedcom": [".ged", ".gedcom"],
    "text/vnd.fly": [".fly"],
    "text/vnd.fmi.flexstor": [".flx"],
    "text/vnd.graphviz": [".gv"],
    "text/vnd.in3d.3dml": [".3dml"],
    "text/vnd.in3d.spot": [".spot"],
    "text/vnd.rn-realtext": [".rt"],
    "text/vnd.senx.warpscript": [".mc2"],
    "text/vnd.sun.j2me.app-descriptor": [".jad"],
    "text/vnd.trolltech.linguist": [".ts"],
    "text/vnd.wap.wml": [".wml"],
    "text/vnd.wap.wmlscript": [".wmls"],
    "text/vtt": [".vtt"],
    "text/x-adasrc": [".adb", ".ads"],
    "text/x-asm": [".s", ".asm"],
    "text/x-authors": [".authors"],
    "text/x-basic": [".bas"],
    "text/x-bibtex": [".bib"],
    "text/x-blueprint": [".blp"],
    "text/x-c": [".c", ".cc", ".cxx", ".cpp", ".h", ".hh", ".dic"],
    "text/x-c++hdr": [".h++", ".hp", ".hpp", ".hxx"],
    "text/x-c++src": [".C", ".c++"],
    "text/x-changelog": [".changelog"],
    "text/x-cmake": [".cmake"],
    "text/x-cobol": [".cbl", ".cob"],
    "text/x-common-lisp": [".asd", ".fasl", ".lisp", ".ros"],
    "text/x-component": [".htc"],
    "text/x-copying": [".copying"],
    "text/x-credits": [".credits"],
    "text/x-crystal": [".cr"],
    "text/x-csharp": [".cs"],
    "text/x-csrc": [".c"],
    "text/x-dbus-service": [".service"],
    "text/x-dcl": [".dcl"],
    "text/x-devicetree-source": [".dtsi"],
    "text/x-dsl": [".dsl"],
    "text/x-dsrc": [".d", ".di"],
    "text/x-eiffel": [".e", ".eif"],
    "text/x-elixir": [".ex", ".exs"],
    "text/x-emacs-lisp": [".el"],
    "text/x-erlang": [".erl"],
    "text/x-fortran": [".f", ".for", ".f77", ".f90", ".f95"],
    "text/x-gcode-gx": [".gx"],
    "text/x-genie": [".gs"],
    "text/x-gettext-translation": [".po"],
    "text/x-gherkin": [".feature"],
    "text/x-go": [".go"],
    "text/x-google-video-pointer": [".gvp"],
    "text/x-gradle": [".gradle"],
    "text/x-groovy": [".groovy", ".gsh", ".gvy", ".gy"],
    "text/x-haskell": [".hs"],
    "text/x-iMelody": [".ime"],
    "text/x-idl": [".idl"],
    "text/x-iptables": [".iptables"],
    "text/x-java": [".java"],
    "text/x-java-source": [".java"],
    "text/x-kaitai-struct": [".ksy"],
    "text/x-kotlin": [".kt"],
    "text/x-ldif": [".ldif"],
    "text/x-lilypond": [".ly"],
    "text/x-literate-haskell": [".lhs"],
    "text/x-log": [".log"],
    "text/x-lua": [".lua"],
    "text/x-makefile": [".mak", ".mk"],
    "text/x-matlab": [".m"],
    "text/x-moc": [".moc"],
    "text/x-mof": [".mof"],
    "text/x-mpl2": [".mpl"],
    "text/x-mrml": [".mrl", ".mrml"],
    "text/x-ms-regedit": [".reg"],
    "text/x-mup": [".mup", ".not"],
    "text/x-nfo": [".nfo"],
    "text/x-nim": [".nim"],
    "text/x-nimscript": [".nimble", ".nims"],
    "text/x-objc++src": [".mm"],
    "text/x-ocaml": [".ml", ".mli"],
    "text/x-ocl": [".ocl"],
    "text/x-ooc": [".ooc"],
    "text/x-opencl-src": [".cl"],
    "text/x-opml": [".opml"],
    "text/x-pascal": [".p", ".pas"],
    "text/x-patch": [".diff", ".patch"],
    "text/x-python": [".py", ".pyx", ".wsgi"],
    "text/x-python3": [".py3", ".py3x", ".pyi"],
    "text/x-qml": [".qml", ".qmlproject", ".qmltypes"],
    "text/x-reject": [".rej"],
    "text/x-rpm-spec": [".spec"],
    "text/x-rst": [".rst"],
    "text/x-sagemath": [".sage"],
    "text/x-sass": [".sass"],
    "text/x-scala": [".scala"],
    "text/x-scheme": [".ss"],
    "text/x-scons": [".sconscript", ".sconstruct"],
    "text/x-script.python": [".py"],
    "text/x-scss": [".scss"],
    "text/x-setext": [".etx"],
    "text/x-sfv": [".sfv"],
    "text/x-sgml": [".sgml"],
    "text/x-ssa": [".ssa"],
    "text/x-svhdr": [".svh"],
    "text/x-svsrc": [".sv"],
    "text/x-systemd-unit": [
        ".automount",
        ".device",
        ".mount",
        ".path",
        ".scope",
        ".slice",
        ".socket",
        ".swap",
        ".target",
        ".timer",
    ],
    "text/x-tex": [".cls", ".dtx", ".ins", ".ltx", ".sty"],
    "text/x-texinfo": [".tex"],
    "text/x-todo-txt": [".todo.txt"],
    "text/x-twig": [".twig"],
    "text/x-txt2tags": [".t2t"],
    "text/x-typst": [".typ"],
    "text/x-uil": [".uil"],
    "text/x-uuencode": [".uu", ".uue"],
    "text/x-vala": [".vala", ".vapi"],
    "text/x-vcalendar": [".vcs"],
    "text/x-vcard": [".vcf"],
    "text/x-verilog": [".v"],
    "text/x-vhdl": [".vhdl"],
    "text/x-xmi": [".xmi"],
    "text/x-xslfo": [".fo", ".xslfo"],
    "text/x.gcode": [".gcode"],
    "text/xml": [".xml"],
    "video/3gpp": [".3gp"],
    "video/3gpp2": [".3gp2"],
    "video/annodex": [".axv"],
    "video/dv": [".dv"],
    "video/h261": [".h261"],
    "video/h263": [".h263"],
    "video/h264": [".h264"],
    "video/jpeg": [".jpgv"],
    "video/jpm": [".jpm"],
    "video/mj2": [".mj2", ".mjp2"],
    "video/mp2t": [".bdmv", ".clpi", ".cpi", ".m2t", ".m2ts", ".mpls"],
    "video/mp4": [".mp4", ".mp4v", ".mpg4", ".lrv"],
    "video/mpeg": [".mpeg", ".mpg", ".mpe", ".m1v", ".m2v"],
    "video/ogg": [".ogv"],
    "video/quicktime": [".qt", ".mov", ".qtvr", ".moov"],
    "video/vnd.avi": [".avf", ".avi", ".divx"],
    "video/vnd.dece.hd": [".uvh", ".uvvh"],
    "video/vnd.dece.mobile": [".uvm", ".uvvm"],
    "video/vnd.dece.pd": [".uvp", ".uvvp"],
    "video/vnd.dece.sd": [".uvs", ".uvvs"],
    "video/vnd.dece.video": [".uvv", ".uvvv"],
    "video/vnd.dvb.file": [".dvb"],
    "video/vnd.fvt": [".fvt"],
    "video/vnd.mpegurl": [".mxu", ".m4u", ".m1u"],
    "video/vnd.ms-playready.media.pyv": [".pyv"],
    "video/vnd.radgamettools.bink": [".bik", ".bk2"],
    "video/vnd.radgamettools.smacker": [".smk"],
    "video/vnd.rn-realvideo": [".rv", ".rvx"],
    "video/vnd.uvvu.mp4": [".uvu", ".uvvu"],
    "video/vnd.vivo": [".viv", ".vivo"],
    "video/vnd.youtube.yt": [".yt"],
    "video/webm": [".webm"],
    "video/x-anim": [".anim[1-9j]"],
    "video/x-f4v": [".f4v"],
    "video/x-fli": [".fli"],
    "video/x-flic": [".flc"],
    "video/x-flv": [".flv"],
    "video/x-javafx": [".fxm"],
    "video/x-m4v": [".m4v"],
    "video/x-matroska": [".mkv", ".mk3d", ".mks"],
    "video/x-mjpeg": [".mjpeg", ".mjpg"],
    "video/x-mng": [".mng"],
    "video/x-ms-asf": [".asf"],
    "video/x-ms-vob": [".vob"],
    "video/x-ms-wm": [".wm"],
    "video/x-ms-wmv": [".wmv"],
    "video/x-ms-wmx": [".wmx"],
    "video/x-ms-wvx": [".wvx"],
    "video/x-nsv": [".nsv"],
    "video/x-ogm+ogg": [".ogm"],
    "video/x-sgi-movie": [".movie"],
    "video/x-smv": [".smv"],
    "x-conference/x-cooltalk": [".ice"],
    "x-epoc/x-sisx-app": [".sisx"],
}

SKIP_DIRS = frozenset({"lazy", ".git", "__pycache__", ".mypy_cache", ".ruff_cache", ".pytest_cache"})


def is_binary(path: Path | str) -> bool:
    path = Path(path)
    try:
        with path.open("rb") as f:
            chunk = f.read(CHUNK_SIZE)
        if not chunk:
            return False
        if b"\x00" in chunk:
            return True
        text_chars = bytearray(range(32, 127)) + b"\n\r\t\x08"
        nontext = sum(1 for b in chunk if b not in text_chars)
        return nontext / len(chunk) > ZERO_DOT_THREE
    except Exception:
        return True


def unique_path(path: Path | str) -> Path:
    path = _clean_fname(Path(path))
    if not path.exists():
        return path
    parent = path.parent
    suffixes = path.suffixes
    if suffixes:
        first_suffix_index = path.name.find(suffixes[0])
        stem = path.name[:first_suffix_index]
        full_suffix = "".join(suffixes)
    else:
        stem = path.name
        full_suffix = ""
    counter = 1
    while True:
        new_name = f"{stem}_{counter}{full_suffix}"
        new_path = parent / new_name
        if not new_path.exists():
            return new_path
        counter += 1


def _clean_fname(path: Path) -> Path:
    from re import sub as re_sub

    clean_name = re_sub(r"(_\d+)+", "", path.name)
    return path.with_name(clean_name)


ATTRIBUTES = {
    "bold": 1,
    "dark": 2,
    "italic": 3,
    "underline": 4,
    "blink": 5,
    "reverse": 7,
    "concealed": 8,
    "strike": 9,
}

HIGHLIGHTS = {
    "on_black": 40,
    "on_grey": 40,
    "on_red": 41,
    "on_green": 42,
    "on_yellow": 43,
    "on_blue": 44,
    "on_magenta": 45,
    "on_cyan": 46,
    "on_light_grey": 47,
    "on_dark_grey": 100,
    "on_light_red": 101,
    "on_light_green": 102,
    "on_light_yellow": 103,
    "on_light_blue": 104,
    "on_light_magenta": 105,
    "on_light_cyan": 106,
    "on_white": 107,
}

COLORS = {
    "black": 30,
    "grey": 30,
    "red": 31,
    "green": 32,
    "yellow": 33,
    "blue": 34,
    "magenta": 35,
    "cyan": 36,
    "light_grey": 37,
    "dark_grey": 90,
    "light_red": 91,
    "light_green": 92,
    "light_yellow": 93,
    "light_blue": 94,
    "light_magenta": 95,
    "light_cyan": 96,
    "white": 97,
}

RESET = "\x1b[0m"


def can_colorize(*, no_color=None, force_color=None):
    if no_color is not None and no_color:
        return False
    if force_color is not None and force_color:
        return True
    if os.environ.get("ANSI_COLORS_DISABLED"):
        return False
    if os.environ.get("NO_COLOR"):
        return False
    if os.environ.get("FORCE_COLOR"):
        return True
    if os.environ.get("TERM") == "dumb":
        return False
    if not hasattr(sys.stdout, "fileno"):
        return False
    try:
        return os.isatty(sys.stdout.fileno())
    except OSError:
        return sys.stdout.isatty()


def colored(text, color=None, on_color=None, attrs=None, *, no_color=None, force_color=None):
    result = str(text)
    if not can_colorize(no_color=no_color, force_color=force_color):
        return result
    fmt_str = "\x1b[%dm%s"
    rgb_fore_fmt_str = "\x1b[38;2;%d;%d;%dm%s"
    rgb_back_fmt_str = "\x1b[48;2;%d;%d;%dm%s"
    if color is not None:
        if isinstance(color, str):
            result = fmt_str % (COLORS[color], result)
        elif isinstance(color, tuple):
            result = rgb_fore_fmt_str % (color[0], color[1], color[2], result)
    if on_color is not None:
        if isinstance(on_color, str):
            result = fmt_str % (HIGHLIGHTS[on_color], result)
        elif isinstance(on_color, tuple):
            result = rgb_back_fmt_str % (on_color[0], on_color[1], on_color[2], result)
    if attrs is not None:
        for attr in attrs:
            result = fmt_str % (ATTRIBUTES[attr], result)
    result += RESET
    return result


def cprint(text, color=None, on_color=None, attrs=None, *, no_color=None, force_color=None, **kwargs):
    print(colored(text, color, on_color, attrs, no_color=no_color, force_color=force_color), **kwargs)


def runcmd(
    cmd: list[str],
    run_silently: bool = False,
    show_output: bool = True,
    timeout: float | None = None,
) -> tuple[int, str, str]:
    from subprocess import DEVNULL as _DEVNULL
    from subprocess import TimeoutExpired as subprocess_TimeoutExpired
    from subprocess import run as subprocess_run
    from sys import stderr as sys_stderr
    from sys import stdout as sys_stdout

    if not cmd:
        msg = "cmd must be a non-empty list (e.g., ['ls', '-l'])"
        raise ValueError(msg)
    try:
        if run_silently:
            result = subprocess_run(cmd, stdout=_DEVNULL, stderr=_DEVNULL, timeout=timeout)
            return result.returncode, "", ""
        result = subprocess_run(cmd, capture_output=True, text=True, timeout=timeout)
        stdout, stderr = result.stdout, result.stderr
        if show_output:
            if stdout:
                sys_stdout.write(stdout)
                sys_stdout.flush()
            if stderr:
                sys_stderr.write(stderr)
                sys_stderr.flush()
        return result.returncode, stdout, stderr
    except FileNotFoundError:
        msg = f"Command not found: '{cmd[0]}'"
        if show_output and not run_silently:
            print(msg, file=sys_stderr)
        return 127, "", msg
    except PermissionError:
        msg = f"Permission denied: '{cmd[0]}'"
        if show_output and not run_silently:
            print(msg, file=sys_stderr)
        return 126, "", msg
    except subprocess_TimeoutExpired:
        msg = f"Command timed out after {timeout}s: {' '.join(cmd)}"
        if show_output and not run_silently:
            print(msg, file=sys_stderr)
        return 124, "", msg
    except Exception as e:
        msg = f"Unexpected error running '{cmd[0]}': {e}"
        if show_output and not run_silently:
            print(msg, file=sys_stderr)
        return 1, "", msg


CONFIRM = "-y" in sys.argv


def fix_by_shebang(path) -> bool:
    if is_binary(path) or not path.stat().st_size:
        return False
    try:
        content = path.read_text(encoding="utf8")
    except:
        return False
    fl = content.splitlines()[0]
    if fl.startswith("#!") and ("bash" in fl or "/bin/sh" in fl):
        new_path = path.with_suffix(".sh")
        if new_path.exists():
            new_path = unique_path(new_path)
        path.rename(new_path)
        return True
    if fl.startswith("#!") and "python" in fl:
        new_path = path.with_suffix(".py")
        if new_path.exists():
            new_path = unique_path(new_path)
        path.rename(new_path)
        return True
    return False


def get_file_mime(path) -> str:
    _, txt, _ = runcmd(["file", "--brief", "--mime-type", str(path)], show_output=False)
    return txt


def safe_rename(old_path, new_path):
    base, ext = os.path.splitext(new_path)
    counter = 1
    while Path(new_path).exists():
        counter += 1
    cprint(f"{old_path} -> {new_path} ?")
    Path(old_path).rename(new_path)
    return new_path


def check_files(directory: Path):
    mismatched_files = []
    for root, _, files in os.walk(directory):
        for name in files:
            path = Path(root) / name
            if ".git" in path.parts or "__pycache__" in path.parts:
                continue
            ext = path.suffix.lower()
            if ext in {".css", ".js"}:
                continue
            if fix_by_shebang(path):
                continue
            mime = get_file_mime(path)
            print(f"{name} --> {mime}")
            if mime:
                print(f"mime={mime}")
                expected_exts = MIME2EXT.get(mime.strip(), [])
                print(f"expected exts ={expected_exts}")
                if ".txt" in expected_exts:
                    continue
                if expected_exts and ext not in expected_exts:
                    new_path = None
                    new_ext = expected_exts[0]
                    new_name = path.stem + new_ext
                    print(f"new name = {new_name}")
                    new_path = Path(root) / new_name
                    if new_name == name:
                        continue
                    if new_path.exists():
                        new_path = unique_path(new_path)
                    if CONFIRM:
                        print(f"{path.suffix} -> {new_path.suffix}")
                        ans = input()
                        if ans == "y":
                            path.rename(new_path)
                    else:
                        path.rename(new_path)
                    mismatched_files.append((path, ext, mime, new_path))
    return mismatched_files


def main() -> None:
    cwd = Path.cwd()
    mismatches = check_files(cwd)
    if mismatches:
        print("Files with mismatched extensions:")
        for path, _ext, mime, new_path in mismatches:
            if new_path:
                print(f"\x1b[5;93m{path.name} {mime} \x1b[5;96m{new_path.name}]\x1b[0m")
            else:
                print(f"{path.name} -> \x1b[5m;94mdetected: {mime}\x1b[0m")
    else:
        cprint("no mismatch")


if __name__ == "__main__":
    main()
