#!/data/data/com.termux/files/usr/bin/env python

import html
from pathlib import Path
from urllib.parse import quote

SKIP_DIRS = frozenset({"lazy", ".git", "__pycache__", ".mypy_cache", ".ruff_cache", ".pytest_cache"})


def fsz(sz: float) -> str:
    sz = abs(int(sz))
    units = "B", "KB", "MB", "GB", "TB"
    if sz == 0:
        return "0 B"
    i = min((int(sz).bit_length() - 1) // 10, len(units) - 1)
    value = sz / 1024**i
    if i == 0:
        return f"{int(value)} {units[i]}"
    return f"{value:.1f} {units[i]}"


cwd = Path.cwd()
FONT_EXT = {".ttf", ".otf", ".woff", ".woff2", ".eot", ".svg"}
SAMPLE_TEXT = """Lorem ipsum dolor sit amet
هنر برتر از گوهر آمد پدید"""
OUTPUT_FILE = "fontpreview.html"
HTML_START = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Font Preview</title>
<style>
:root {
  --bg:
  --text:
  --border:
  --accent:
  --input-bg:
}
@media (prefers-color-scheme: light) {
  :root {
    --bg:
    --text:
    --border:
    --accent:
    --input-bg:
  }
}
body {
  background: var(--bg);
  color: var(--text);
  font-family: system-ui, -apple-system, sans-serif;
  margin: 0 auto;
  padding: 20px;
  max-width: 960px;
  transition: background 0.3s, color 0.3s;
}
h1 {
  margin-top: 40px;
  font-size: 1.6em;
  border-bottom: 2px solid var(--border);
  padding-bottom: .3em;
  color: var(--accent);
}
textarea {
  width: 100%;
  min-height: 100px;
  padding: 16px;
  margin-top: 6px;
  border-radius: 8px;
  border: 2px solid var(--border);
  font-size: clamp(1em, 2vw, 1.5em);
  box-sizing: border-box;
  resize: vertical;
  white-space: pre-wrap;
  background: var(--input-bg);
  color: var(--text);
  transition: border-color 0.3s;
  line-height: 1.6;
}
textarea:focus {
  outline: none;
  border-color: var(--accent);
}
section {
  margin-top: 30px;
  padding-bottom: 20px;
  border-bottom: 2px solid var(--border);
}
.note {
  color:
  margin-top: 8px;
  font-size: 0.85em;
  font-family: monospace;
  word-break: break-all;
}
footer {
  margin-top: 40px;
  text-align: center;
  color:
  font-size: 0.9em;
}
</style>
</head>
<body>
<h1> Font Preview</h1>
<p class="note">Automatically generated preview for all fonts</p>
"""
HTML_END = """
<footer>Generated by me </footer>
</body></html>"""


def find_fonts(root=None):
    if root is None:
        root = cwd
    found = []
    try:
        for path in root.rglob("*"):
            if path.is_file() and path.suffix.lower() in FONT_EXT:
                found.append(path)
    except PermissionError:
        print(f"Warning: Permission denied accessing some directories")
    return sorted(found)


def create_font_face(path, font_id: str) -> str:
    try:
        rel_path = path.relative_to(cwd)
        url_path = quote(str(rel_path.as_posix()))
        return f"""@font-face {{
  font-family: 'font_{font_id}';
  src: url('{url_path}');
  font-display: swap;
}}"""
    except ValueError:
        url_path = quote(str(path.as_posix()))
        return f"""@font-face {{
  font-family: 'font_{font_id}';
  src: url('file:///{url_path}');
  font-display: swap;
}}"""


def generate_preview(fonts) -> str:
    styles = []
    sections = []
    for i, font_path in enumerate(fonts, 1):
        font_id = f"{i:03d}"
        font_name = font_path.name
        font_format = font_path.suffix.upper().lstrip(".")
        styles.append(create_font_face(font_path, font_id))
        escaped_sample = html.escape(SAMPLE_TEXT)
        file_size = font_path.stat().st_size if font_path.exists() else 0
        size_str = f"{fsz(file_size)}"
        sections.append(f"""
<section>
  <h1 style="font-family: 'font_{font_id}';">{html.escape(font_name)} <small style="font-size:0.6em;opacity:0.7">({font_format})</small></h1>
  <textarea
    style="font-family: 'font_{font_id}', sans-serif;"
    spellcheck="false"
    placeholder="Type to test font..."
  >{escaped_sample}</textarea>
  <p class="note">{html.escape(str(font_path.name))} | {size_str}</p>
</section>""")
    style_block = "\n".join(styles)
    sections_block = "".join(sections)
    html_content = HTML_START.replace("</style>", f"\n{style_block}\n</style>")
    html_content += sections_block + HTML_END
    return html_content


def main() -> None:
    fonts = find_fonts()
    if not fonts:
        print("❌ No font files found in current directory.")
        print(f"   Supported formats: {', '.join(sorted(FONT_EXT))}")
        return
    print(f"✓ Found {len(fonts)} font(s)")
    html_content = generate_preview(fonts)
    output_path = cwd / OUTPUT_FILE
    output_path.write_text(html_content, encoding="utf-8")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n⚠️  Operation cancelled by user")
    except Exception as e:
        print(f"❌ Error: {e}")
