#!/data/data/com.termux/files/usr/bin/python

import html
from pathlib import Path
from urllib.parse import quote
from dh import fsz

cwd = Path.cwd()
FONT_EXT = {".ttf", ".otf", ".woff", ".woff2", ".eot", ".svg"}
SAMPLE_TEXT = "Lorem ipsum dolor sit amet\nهنر برتر از گوهر آمد پدید"
OUTPUT_FILE = "fontpreview.html"
HTML_START = '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>Font Preview</title>\n<style>\n:root {\n  --bg:\n  --text:\n  --border:\n  --accent:\n  --input-bg:\n}\n@media (prefers-color-scheme: light) {\n  :root {\n    --bg:\n    --text:\n    --border:\n    --accent:\n    --input-bg:\n  }\n}\nbody {\n  background: var(--bg);\n  color: var(--text);\n  font-family: system-ui, -apple-system, sans-serif;\n  margin: 0 auto;\n  padding: 20px;\n  max-width: 960px;\n  transition: background 0.3s, color 0.3s;\n}\nh1 {\n  margin-top: 40px;\n  font-size: 1.6em;\n  border-bottom: 2px solid var(--border);\n  padding-bottom: .3em;\n  color: var(--accent);\n}\ntextarea {\n  width: 100%;\n  min-height: 100px;\n  padding: 16px;\n  margin-top: 6px;\n  border-radius: 8px;\n  border: 2px solid var(--border);\n  font-size: clamp(1em, 2vw, 1.5em);\n  box-sizing: border-box;\n  resize: vertical;\n  white-space: pre-wrap;\n  background: var(--input-bg);\n  color: var(--text);\n  transition: border-color 0.3s;\n  line-height: 1.6;\n}\ntextarea:focus {\n  outline: none;\n  border-color: var(--accent);\n}\nsection {\n  margin-top: 30px;\n  padding-bottom: 20px;\n  border-bottom: 2px solid var(--border);\n}\n.note {\n  color:\n  margin-top: 8px;\n  font-size: 0.85em;\n  font-family: monospace;\n  word-break: break-all;\n}\nfooter {\n  margin-top: 40px;\n  text-align: center;\n  color:\n  font-size: 0.9em;\n}\n</style>\n</head>\n<body>\n<h1> Font Preview</h1>\n<p class="note">Automatically generated preview for all fonts</p>\n'
HTML_END = "\n<footer>Generated by me </footer>\n</body></html>"


def find_fonts(root=None):
    if root is None:
        root = cwd
    found = []
    try:
        for path in root.rglob("*"):
            if path.is_file() and path.suffix.lower() in FONT_EXT:
                found.append(path)
    except PermissionError:
        print(f"Warning: Permission denied accessing some directories")
    return sorted(found)


def create_font_face(path, font_id):
    try:
        rel_path = path.relative_to(cwd)
        url_path = quote(str(rel_path.as_posix()))
        return f"@font-face {{\n  font-family: 'font_{font_id}';\n  src: url('{url_path}');\n  font-display: swap;\n}}"
    except ValueError:
        url_path = quote(str(path.as_posix()))
        return f"@font-face {{\n  font-family: 'font_{font_id}';\n  src: url('file:///{url_path}');\n  font-display: swap;\n}}"


def generate_preview(fonts):
    """Generate complete HTML with font previews."""
    styles = []
    sections = []
    for i, font_path in enumerate(fonts, 1):
        font_id = f"{i:03d}"
        font_name = font_path.name
        font_format = font_path.suffix.upper().lstrip(".")
        styles.append(create_font_face(font_path, font_id))
        escaped_sample = html.escape(SAMPLE_TEXT)
        file_size = font_path.stat().st_size if font_path.exists() else 0
        size_str = f"{fsz(file_size)}"
        sections.append(
            f"""\n<section>\n  <h1 style="font-family: 'font_{font_id}';">{html.escape(font_name)} <small style="font-size:0.6em;opacity:0.7">({font_format})</small></h1>\n  <textarea\n    style="font-family: 'font_{font_id}', sans-serif;"\n    spellcheck="false"\n    placeholder="Type to test font..."\n  >{escaped_sample}</textarea>\n  <p class="note">{html.escape(str(font_path.name))} | {size_str}</p>\n</section>"""
        )
    style_block = "\n".join(styles)
    sections_block = "".join(sections)
    html_content = HTML_START.replace("</style>", f"\n{style_block}\n</style>")
    html_content += sections_block + HTML_END
    return html_content


def main():
    """Main execution function."""
    fonts = find_fonts()
    if not fonts:
        print("❌ No font files found in current directory.")
        print(f"   Supported formats: {', '.join(sorted(FONT_EXT))}")
        return
    print(f"✓ Found {len(fonts)} font(s)")
    html_content = generate_preview(fonts)
    output_path = cwd / OUTPUT_FILE
    output_path.write_text(html_content, encoding="utf-8")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n⚠️  Operation cancelled by user")
    except Exception as e:
        print(f"❌ Error: {e}")
