#!/data/data/com.termux/files/usr/bin/env python
from typing import Optional

"""
HTML Minifier - Python wrapper for html-minifier-terser
Minifies HTML files recursively with parallel processing.
"""

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path

from colorama import Fore, Style, init

# Initialize colorama for cross-platform colored output
init(autoreset=True)


@dataclass
class MinifyStats:
    """Statistics for a minified file."""

    path: Path
    original_size: int
    minified_size: int
    success: bool
    error: str = ""

    @property
    def ratio(self) -> float:
        """Calculate compression ratio."""
        if self.original_size == 0:
            return 0.0
        return (1 - self.minified_size / self.original_size) * 100

    @property
    def saved(self) -> int:
        """Calculate bytes saved."""
        return self.original_size - self.minified_size


class HTMLMinifier:
    """HTML minifier wrapper using html-minifier-terser via npm."""

    # Default configuration optimized for comprehensive but safe minification
    DEFAULT_CONFIG = {
        # Whitespace & formatting
        "collapseWhitespace": True,
        "collapseInlineTagWhitespace": True,
        "conservativeCollapse": True,  # Ensures at least one space is kept in important places
        "preserveLineBreaks": False,
        "removeTagWhitespace": False,  # Can cause issues with inline elements
        # Comments
        "removeComments": True,
        # Attributes
        "removeRedundantAttributes": True,
        "removeEmptyAttributes": True,
        "removeAttributeQuotes": False,  # Keep quotes for safety
        "collapseBooleanAttributes": True,
        "useShortDoctype": False,  # Keep full doctype for compatibility
        "keepClosingSlash": False,
        # Scripts & styles
        "removeScriptTypeAttributes": True,
        "removeStyleLinkTypeAttributes": True,
        "minifyCSS": True,
        "minifyJS": True,
        "minifyURLs": True,
        # Tags
        "removeEmptyElements": False,  # Can remove needed empty elements
        "removeOptionalTags": False,  # THIS was causing the doctype issue
        # Entities & special chars
        "decodeEntities": True,
        "preventAttributesEscaping": False,
        "quoteCharacter": '"',
        # HTML5
        "html5": True,
        "includeAutoGeneratedTags": False,
        # Processing
        "processConditionalComments": True,
        "processScripts": ["text/html"],
        # Sorting
        "sortAttributes": True,
        "sortClassName": True,
        # Custom fragments
        "trimCustomFragments": True,
    }

    # Alternative: More aggressive config (use with caution)
    AGGRESSIVE_CONFIG = {
        "collapseWhitespace": True,
        "collapseInlineTagWhitespace": True,
        "conservativeCollapse": False,
        "preserveLineBreaks": False,
        "removeTagWhitespace": True,
        "removeComments": True,
        "removeRedundantAttributes": True,
        "removeEmptyAttributes": True,
        "removeAttributeQuotes": True,
        "collapseBooleanAttributes": True,
        "useShortDoctype": True,
        "keepClosingSlash": False,
        "removeScriptTypeAttributes": True,
        "removeStyleLinkTypeAttributes": True,
        "minifyCSS": True,
        "minifyJS": True,
        "minifyURLs": True,
        "removeEmptyElements": True,
        "removeOptionalTags": True,
        "decodeEntities": True,
        "preventAttributesEscaping": False,
        "quoteCharacter": '"',
        "html5": True,
        "includeAutoGeneratedTags": False,
        "processConditionalComments": True,
        "processScripts": ["text/html"],
        "sortAttributes": True,
        "sortClassName": True,
        "trimCustomFragments": True,
        # Post-processing hook to fix doctype
    }

    def __init__(self, config: Optional[dict] = None, aggressive: bool = False):
        """Initialize minifier with custom or default config."""
        if config:
            self.config = config
        elif aggressive:
            self.config = self.AGGRESSIVE_CONFIG.copy()
        else:
            self.config = self.DEFAULT_CONFIG.copy()
        self.aggressive = aggressive
        self._check_dependencies()

    @staticmethod
    def _check_dependencies() -> None:
        """Check if html-minifier-terser is installed."""
        if not shutil.which("html-minifier-terser"):
            print(f"{Fore.RED}Error: html-minifier-terser is not installed.{Style.RESET_ALL}")
            print(f"{Fore.YELLOW}Install it with: npm install -g html-minifier-terser{Style.RESET_ALL}")
            sys.exit(1)

    @staticmethod
    def _fix_doctype(content: str) -> str:
        """Fix common doctype issues introduced by minification."""
        # Fix <!doctypehtml> -> <!doctype html>
        import re

        content = re.sub(r"<!(doctype)(html)", r"<!\1 \2", content, flags=re.IGNORECASE)
        # Fix <!DOCTYPEhtml> -> <!DOCTYPE html>
        content = re.sub(r"<!(DOCTYPE)(HTML)", r"<!\1 \2", content)
        return content

    @staticmethod
    def _post_process(content: str, aggressive: bool = False) -> str:
        """Post-process minified content to fix issues."""
        # Always fix doctype
        content = HTMLMinifier._fix_doctype(content)

        if aggressive:
            # Additional fixes for aggressive mode
            # Ensure space before closing tags in certain cases
            import re

            # Fix potential issues with inline elements merging
            content = re.sub(
                r"(</(?:span|a|strong|em|b|i|code|label)>)"
                r"(<(?:span|a|strong|em|b|i|code|label))",
                r"\1 \2",
                content,
            )

        return content

    def _build_cli_args(self, config_file: Path) -> list[str]:
        """Build command-line arguments from config."""
        args = ["html-minifier-terser", "--config-file", str(config_file)]
        return args

    def minify_file(self, file_path: Path) -> MinifyStats:
        """Minify a single HTML file."""
        config_file = None
        try:
            original_size = file_path.stat().st_size

            # Create a temporary config file
            with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8") as f:
                json.dump(self.config, f)
                config_file = Path(f.name)

            # Read input file
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()

            # Build command with config file
            cmd = self._build_cli_args(config_file)

            # Run html-minifier-terser
            process = subprocess.run(cmd, input=content, capture_output=True, text=True, encoding="utf-8")

            if process.returncode != 0:
                return MinifyStats(
                    path=file_path,
                    original_size=original_size,
                    minified_size=original_size,
                    success=False,
                    error=f"Minification failed: {process.stderr.strip()}",
                )

            # Post-process the minified content
            minified_content = self._post_process(process.stdout, aggressive=self.aggressive)

            # Write minified content back to file
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(minified_content)

            minified_size = file_path.stat().st_size

            return MinifyStats(path=file_path, original_size=original_size, minified_size=minified_size, success=True)

        except Exception as e:
            return MinifyStats(path=file_path, original_size=0, minified_size=0, success=False, error=str(e))
        finally:
            # Clean up config file
            if config_file and config_file.exists():
                try:
                    config_file.unlink()
                except Exception:
                    pass

    @staticmethod
    def find_html_files(directories: list[Path]) -> list[Path]:
        """Find all HTML files in given directories recursively."""
        html_files = []
        for directory in directories:
            if not directory.exists():
                print(f"{Fore.YELLOW}Warning: Directory '{directory}' does not exist. Skipping.{Style.RESET_ALL}")
                continue
            if not directory.is_dir():
                print(f"{Fore.YELLOW}Warning: '{directory}' is not a directory. Skipping.{Style.RESET_ALL}")
                continue

            # Find all .html and .htm files
            html_files.extend(directory.rglob("*.html"))
            html_files.extend(directory.rglob("*.htm"))

        return sorted(set(html_files))  # Remove duplicates and sort

    def minify_directory(self, directories: list[Path], max_workers: int = 4) -> None:
        """Minify all HTML files in directories using parallel processing."""
        html_files = self.find_html_files(directories)

        if not html_files:
            print(f"{Fore.YELLOW}No HTML files found to minify.{Style.RESET_ALL}")
            return

        total_files = len(html_files)
        print(f"\n{Fore.CYAN}Found {total_files} HTML file(s) to minify{Style.RESET_ALL}")
        if self.aggressive:
            print(f"{Fore.YELLOW}⚠️  Using aggressive mode - review output carefully{Style.RESET_ALL}")
        print(f"{Fore.CYAN}{'=' * 60}{Style.RESET_ALL}\n")

        stats_list: list[MinifyStats] = []
        successful = 0
        failed = 0
        total_original = 0
        total_minified = 0

        # Process files in parallel
        with ThreadPoolExecutor(max_workers=8) as executor:
            future_to_file = {executor.submit(self.minify_file, file_path): file_path for file_path in html_files}

            for future in as_completed(future_to_file):
                stats = future.result()
                stats_list.append(stats)

                if stats.success:
                    successful += 1
                    total_original += stats.original_size
                    total_minified += stats.minified_size
                    self._print_file_stats(stats)
                else:
                    failed += 1
                    self._print_error(stats)

        # Print summary
        self._print_summary(total_files, successful, failed, total_original, total_minified)

    def _print_file_stats(self, stats: MinifyStats) -> None:
        """Print statistics for a single file in prettier-style format."""
        try:
            rel_path = stats.path.relative_to(Path.cwd())
        except ValueError:
            rel_path = stats.path

        # Format sizes
        original_kb = stats.original_size / 1024
        minified_kb = stats.minified_size / 1024
        saved_kb = stats.saved / 1024

        # Color based on compression ratio
        if stats.ratio > 30:
            ratio_color = Fore.GREEN
        elif stats.ratio > 10:
            ratio_color = Fore.YELLOW
        else:
            ratio_color = Fore.RED

        # Show a checkmark for successful files
        print(
            f"{Fore.GREEN}✓{Style.RESET_ALL} {Fore.WHITE}{rel_path}{Style.RESET_ALL}\n"
            f"  {Fore.BLUE}Original: {original_kb:.2f} KB{Style.RESET_ALL}  "
            f"{ratio_color}→ {minified_kb:.2f} KB{Style.RESET_ALL}  "
            f"{Fore.MAGENTA}(-{saved_kb:.2f} KB, {ratio_color}{stats.ratio:.1f}%{Style.RESET_ALL}{Fore.MAGENTA}){Style.RESET_ALL}"
        )

    def _print_error(self, stats: MinifyStats) -> None:
        """Print error for a failed file."""
        try:
            rel_path = stats.path.relative_to(Path.cwd())
        except ValueError:
            rel_path = stats.path

        print(f"{Fore.RED}✗ {rel_path}{Style.RESET_ALL}\n  {Fore.RED}Error: {stats.error}{Style.RESET_ALL}")

    def _print_summary(
        self, total: int, successful: int, failed: int, total_original: int, total_minified: int
    ) -> None:
        """Print overall summary statistics."""
        total_saved = total_original - total_minified
        overall_ratio = (total_saved / total_original * 100) if total_original > 0 else 0

        original_mb = total_original / (1024 * 1024)
        minified_mb = total_minified / (1024 * 1024)
        saved_mb = total_saved / (1024 * 1024)

        print(f"\n{Fore.CYAN}{'=' * 60}{Style.RESET_ALL}")
        print(f"{Fore.CYAN}Summary{Style.RESET_ALL}")
        print(f"{Fore.CYAN}{'=' * 60}{Style.RESET_ALL}")
        print(f"{Fore.WHITE}Files processed:  {total}{Style.RESET_ALL}")
        print(f"{Fore.GREEN}✓ Successful:     {successful}{Style.RESET_ALL}")
        if failed > 0:
            print(f"{Fore.RED}✗ Failed:         {failed}{Style.RESET_ALL}")
        print(f"{Fore.WHITE}Original size:    {original_mb:.2f} MB{Style.RESET_ALL}")
        print(f"{Fore.WHITE}Minified size:    {minified_mb:.2f} MB{Style.RESET_ALL}")
        print(f"{Fore.GREEN}Total saved:      {saved_mb:.2f} MB ({overall_ratio:.1f}%){Style.RESET_ALL}")
        print(f"{Fore.CYAN}{'=' * 60}{Style.RESET_ALL}\n")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Minify HTML files recursively using html-minifier-terser",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                          # Minify all HTML files in current directory
  %(prog)s public/ dist/            # Minify HTML files in specific directories
  %(prog)s --workers 8 src/         # Use 8 parallel workers
  %(prog)s --aggressive             # Use aggressive minification (review output!)
        """,
    )
    parser.add_argument(
        "directories", nargs="*", default=["."], help="Directories to process (default: current directory)"
    )
    parser.add_argument("-w", "--workers", type=int, default=4, help="Number of parallel workers (default: 4)")
    parser.add_argument(
        "--aggressive", action="store_true", help="Use aggressive minification settings (may cause issues)"
    )
    parser.add_argument("--no-color", action="store_true", help="Disable colored output")

    args = parser.parse_args()

    # Disable colors if requested
    if args.no_color:
        init(strip=True, autostop=False)

    # Convert directory strings to Path objects
    directories = [Path(d).resolve() for d in args.directories]

    # Initialize and run minifier
    minifier = HTMLMinifier(aggressive=args.aggressive)
    minifier.minify_directory(directories, max_workers=args.workers)


if __name__ == "__main__":
    main()
