#!/data/data/com.termux/files/usr/bin/env python


from pathlib import Path
from random import choice as random_choice

extensions = [
    ".3dml",
    ".3ds",
    ".3g2",
    ".ABOUT",
    ".APACHE2",
    ".BSD",
    ".BSD-3-Clause",
    ".CDDL",
    ".GPL",
    ".GS",
    ".MIT",
    ".Rmd",
    ".SHA256SUM",
    ".TAG",
    ".TXT",
    ".aac",
    ".ac",
    ".acc",
    ".ace",
    ".acutc",
    ".aff",
    ".affix",
    ".afp",
    ".ai",
    ".aifc",
    ".am",
    ".ambdec",
    ".ansitxt",
    ".apk",
    ".app",
    ".applescript",
    ".arc",
    ".arx",
    ".asd",
    ".asf",
    ".asm",
    ".atc",
    ".atlas",
    ".atx",
    ".au",
    ".auto_dockerfile",
    ".avi",
    ".avif",
    ".aw",
    ".awk",
    ".azf",
    ".azs",
    ".bash",
    ".bash-completion",
    ".bat",
    ".bcpio",
    ".bdm",
    ".bfd",
    ".bfs",
    ".bib",
    ".bki",
    ".bld",
    ".bmp",
    ".body",
    ".bugfix",
    ".bz",
    ".c11amc",
    ".c4u",
    ".cab",
    ".cache-9",
    ".cc",
    ".cdf",
    ".cdkey",
    ".cff",
    ".chat",
    ".cii",
    ".cmc",
    ".cmd",
    ".co",
    ".cod",
    ".com",
    ".common",
    ".cpp",
    ".crdownload",
    ".cryptonote",
    ".cset",
    ".csh",
    ".css",
    ".cst",
    ".csv",
    ".cts",
    ".curl",
    ".cxx",
    ".d",
    ".dat",
    ".data",
    ".db",
    ".dbk",
    ".dbus",
    ".dd",
    ".dd2",
    ".de",
    ".deb",
    ".def",
    ".der",
    ".desktop",
    ".dgc",
    ".dic",
    ".disable_highdpi",
    ".dist",
    ".djvu",
    ".dl",
    ".dmg",
    ".dms",
    ".doc",
    ".docbook",
    ".doctest",
    ".docx",
    ".dotm",
    ".dpg",
    ".dpkg-old",
    ".dra",
    ".drpm",
    ".dtb",
    ".dtd",
    ".dump",
    ".dvi",
    ".dxp",
    ".dxr",
    ".ecelp9600",
    ".edm",
    ".egg",
    ".ei6",
    ".elv",
    ".emf",
    ".emma",
    ".emz",
    ".en",
    ".end",
    ".ent",
    ".env",
    ".eot",
    ".eps",
    ".epub",
    ".er",
    ".es",
    ".esf",
    ".et",
    ".etx",
    ".evy",
    ".exclude",
    ".exe",
    ".exi",
    ".ext",
    ".ez2",
    ".ez3",
    ".f4v",
    ".fast",
    ".fbs",
    ".fdf",
    ".fe_launch",
    ".feature-removal-schedule",
    ".fgd",
    ".fh",
    ".fh5",
    ".fhc",
    ".fig",
    ".flac",
    ".flc",
    ".flf",
    ".fli",
    ".flo",
    ".flow",
    ".flv",
    ".flw",
    ".fnc",
    ".fontified",
    ".for",
    ".fs",
    ".fsc",
    ".fst",
    ".ftc",
    ".fxp",
    ".fxpl",
    ".fz",
    ".fzs",
    ".g3",
    ".g4",
    ".ga",
    ".gam",
    ".gbr",
    ".gca",
    ".gep",
    ".gex",
    ".ggb",
    ".ggt",
    ".gif",
    ".gim",
    ".gir",
    ".global",
    ".glsl",
    ".gmx",
    ".gnumeric",
    ".gpg",
    ".gpl",
    ".gpx",
    ".gqf",
    ".gram",
    ".gresource",
    ".grxml",
    ".gtm",
    ".gtw",
    ".guess",
    ".gv",
    ".gyp",
    ".gypi",
    ".h",
    ".h2",
    ".hal",
    ".hash",
    ".hdf",
    ".heif",
    ".hhc",
    ".hint",
    ".history",
    ".hpid",
    ".hqx",
    ".htke",
    ".html",
    ".hvd",
    ".hvp",
    ".hxx",
    ".i2g",
    ".icc",
    ".ico",
    ".idx",
    ".igm",
    ".igs",
    ".imp",
    ".in",
    ".inc",
    ".info",
    ".info-3",
    ".install",
    ".iota",
    ".ipfix",
    ".is",
    ".iso",
    ".its",
    ".jad",
    ".jar",
    ".jinja2",
    ".jlt",
    ".jpeg",
    ".jpg",
    ".jpm",
    ".js",
    ".json",
    ".jsonl",
    ".jsonml",
    ".jwt",
    ".jxl",
    ".kar",
    ".karbon",
    ".kbd",
    ".kfo",
    ".kml",
    ".kmz",
    ".kn",
    ".knp",
    ".kpr",
    ".kpxx",
    ".ktx",
    ".ktz",
    ".kv",
    ".kwt",
    ".l",
    ".la",
    ".lasxml",
    ".latex",
    ".ld",
    ".lha",
    ".lib",
    ".license",
    ".lisp",
    ".list",
    ".list3820",
    ".listafp",
    ".ll",
    ".lnk",
    ".loas",
    ".local",
    ".log",
    ".lrf",
    ".lrm",
    ".lrz",
    ".lst",
    ".ltf",
    ".lv",
    ".lvp",
    ".lwp",
    ".lzma",
    ".m14",
    ".m3u",
    ".m3u8",
    ".m4a",
    ".m4f",
    ".m4v",
    ".ma",
    ".mag",
    ".man",
    ".map",
    ".mar",
    ".markdown",
    ".md",
    ".md5sums",
    ".mdi",
    ".mdx",
    ".md~",
    ".me",
    ".menu",
    ".mesh",
    ".metainfo",
    ".mgz",
    ".mid",
    ".midi",
    ".mie",
    ".mirrors",
    ".mjpeg",
    ".mkv",
    ".mmf",
    ".mo",
    ".mod",
    ".modulemap",
    ".mov",
    ".mp2a",
    ".mp3",
    ".mp4",
    ".mp4a",
    ".mp4v",
    ".mpc",
    ".mpe",
    ".mpg",
    ".mpg4",
    ".mpga",
    ".mplstyle",
    ".mpm",
    ".mpn",
    ".mpp",
    ".mpt",
    ".mpy",
    ".mr",
    ".mrc",
    ".mscml",
    ".mseq",
    ".msg",
    ".msh",
    ".msi",
    ".msl",
    ".msty",
    ".mts",
    ".musicxml",
    ".mustache",
    ".mvb",
    ".mvg",
    ".mwf",
    ".mxf",
    ".mxl",
    ".mxs",
    ".mxu",
    ".nanorc",
    ".nbp",
    ".nc",
    ".net",
    ".network",
    ".nfo",
    ".ngdat",
    ".nix",
    ".nlu",
    ".nml",
    ".nnd",
    ".nns",
    ".nnw",
    ".npx",
    ".npy",
    ".npz",
    ".nsc",
    ".nsf",
    ".nt",
    ".ntf",
    ".nu",
    ".nuv",
    ".nvim",
    ".nzb",
    ".o",
    ".oa2",
    ".oa3",
    ".oas",
    ".obj",
    ".obstack",
    ".oda",
    ".odb",
    ".odf",
    ".odg",
    ".ogv",
    ".ok",
    ".old",
    ".opus",
    ".or",
    ".ordering",
    ".org",
    ".otf",
    ".p7r",
    ".pcx",
    ".pdf",
    ".pfb",
    ".pfx",
    ".pgm",
    ".pgp",
    ".pickle",
    ".pki",
    ".plf",
    ".png",
    ".pnm",
    ".portpkg",
    ".potx",
    ".ppd",
    ".pps",
    ".ppsm",
    ".pqa",
    ".prerm",
    ".prf",
    ".pro",
    ".prop",
    ".properties",
    ".props",
    ".prs",
    ".ps",
    ".psb",
    ".pskcxml",
    ".pub",
    ".pwn",
    ".py-tpl",
    ".pyc",
    ".pyf",
    ".pyi",
    ".python",
    ".pyv",
    ".pyw",
    ".pyx",
    ".qfx",
    ".qm",
    ".qwd",
    ".ra",
    ".rc",
    ".ref",
    ".rels",
    ".rep",
    ".rgb",
    ".rip",
    ".rm",
    ".rmi",
    ".rpm",
    ".rpss",
    ".rq",
    ".rs",
    ".rst",
    ".rtx",
    ".rules",
    ".rz",
    ".s",
    ".s3m",
    ".saf",
    ".sar",
    ".saver",
    ".sc",
    ".sci",
    ".scm",
    ".scpp",
    ".scq",
    ".scs",
    ".scss",
    ".scurl",
    ".sda",
    ".sdc",
    ".sdd",
    ".sdkd",
    ".sdkm",
    ".sdp",
    ".sdw",
    ".se",
    ".sed",
    ".see",
    ".seed",
    ".sema",
    ".semd",
    ".semf",
    ".ser",
    ".service",
    ".setpay",
    ".setreg",
    ".settings",
    ".sfd",
    ".sfd-hdstx",
    ".sfv",
    ".sgi",
    ".sgm",
    ".sgml.sh",
    ".sh",
    ".shar",
    ".shell",
    ".shlib",
    ".sig",
    ".sil",
    ".simple",
    ".sip5",
    ".sitx",
    ".skip",
    ".skp",
    ".sldm",
    ".sldx",
    ".slo",
    ".sm",
    ".smf",
    ".smil",
    ".smzip",
    ".snd",
    ".snf",
    ".so",
    ".spec",
    ".spl",
    ".spp",
    ".spx",
    ".sql",
    ".src",
    ".srt",
    ".sru",
    ".ssdl",
    ".ssml",
    ".std",
    ".stderr",
    ".stdlib",
    ".stf",
    ".stk",
    ".stl",
    ".stop",
    ".storyboard",
    ".stp",
    ".stw",
    ".sty",
    ".sub",
    ".subst",
    ".sum",
    ".sus",
    ".sv",
    ".svc",
    ".svg",
    ".svgz",
    ".swa",
    ".swf",
    ".swg",
    ".swi",
    ".swift",
    ".swm",
    ".swp",
    ".sxc",
    ".sxd",
    ".sxg",
    ".sxi",
    ".sxm",
    ".sxw",
    ".sym",
    ".syms",
    ".syn",
    ".syntax",
    ".t",
    ".t7z",
    ".ta",
    ".tab",
    ".table",
    ".tag",
    ".taglet",
    ".tao",
    ".tar",
    ".tarball",
    ".targ",
    ".target",
    ".taz",
    ".tbz",
    ".tcap",
    ".tcl",
    ".td",
    ".tech",
    ".teicorpus",
    ".terms",
    ".texinfo",
    ".tga",
    ".theme",
    ".thrift",
    ".thumbnailer",
    ".tif",
    ".tiktoken",
    ".tlz",
    ".tm",
    ".tmlanguage",
    ".tmo",
    ".tmp",
    ".tmpl",
    ".toml",
    ".torrent",
    ".tpl",
    ".tplx",
    ".tpt",
    ".tra",
    ".train",
    ".traineddata",
    ".trig",
    ".trm",
    ".ts",
    ".tsv",
    ".ttf",
    ".ttl",
    ".tw",
    ".txd",
    ".txt",
    ".typed",
    ".typelib",
    ".tz",
    ".tzst",
    ".u32",
    ".ucf-dist",
    ".ucf-old",
    ".udeb",
    ".ufd",
    ".ufdl",
    ".ui",
    ".ulx",
    ".umj",
    ".unicode",
    ".unityweb",
    ".universal-ctags",
    ".uoml",
    ".upp",
    ".uri",
    ".uris",
    ".url",
    ".urls",
    ".ustar",
    ".utz",
    ".uu",
    ".uva",
    ".uvd",
    ".uvf",
    ".uvg",
    ".uvh",
    ".uvi",
    ".uvp",
    ".uvt",
    ".uvu",
    ".uvv",
    ".uvvd",
    ".uvvf",
    ".uvvg",
    ".uvvm",
    ".uvvt",
    ".uvvx",
    ".uvz",
    ".vcf",
    ".vcx",
    ".vob",
    ".vox",
    ".vs",
    ".vsd",
    ".vsmacros",
    ".vsw",
    ".vxml",
    ".wasm",
    ".wav",
    ".wbmp",
    ".wbs",
    ".wcm",
    ".wdp",
    ".weba",
    ".webmanifest",
    ".webp",
    ".wks",
    ".wma",
    ".wmf",
    ".wml",
    ".wmx",
    ".woff",
    ".woff2",
    ".wordlist",
    ".wpd",
    ".wpl",
    ".wps",
    ".wqd",
    ".wri",
    ".wrl",
    ".wsdl",
    ".wspolicy",
    ".wtb",
    ".x",
    ".x32",
    ".x3d",
    ".x3db",
    ".x3dbz",
    ".x3dvz",
    ".x3dz",
    ".xaml",
    ".xar",
    ".xbd",
    ".xbm",
    ".xbn",
    ".xc",
    ".xce",
    ".xcer",
    ".xcscheme",
    ".xcsettings",
    ".xd",
    ".xdce",
    ".xdcer",
    ".xder",
    ".xdm",
    ".xdp",
    ".xdssc",
    ".xdw",
    ".xdwe",
    ".xdwer",
    ".xe",
    ".xer",
    ".xfdf",
    ".xfdl",
    ".xhvml",
    ".xif",
    ".xla",
    ".xlc",
    ".xlf",
    ".xlsb",
    ".xlsm",
    ".xlsx",
    ".xlt",
    ".xlw",
    ".xml",
    ".xn",
    ".xo",
    ".xpi",
    ".xpm",
    ".xpr",
    ".xps",
    ".xpw",
    ".xpx",
    ".xr",
    ".xsc",
    ".xsce",
    ".xsd10",
    ".xsd11",
    ".xsl",
    ".xslt",
    ".xspf",
    ".xsw",
    ".xswe",
    ".xswer",
    ".xul",
    ".xvm",
    ".xvml",
    ".xwd",
    ".xwer",
    ".xyz",
    ".xz",
    ".y",
    ".yaml",
    ".yang",
    ".yapf",
    ".ycp",
    ".yin",
    ".yml",
    ".yue",
    ".yuv",
    ".yy",
    ".z",
    ".z1",
    ".z2",
    ".z3",
    ".z4",
    ".z5",
    ".z6",
    ".z7",
    ".z8",
    ".zaz",
    ".zcml",
    ".zi",
    ".zip",
    ".zir",
    ".zirz",
    ".zmm",
    ".zon",
    ".zoo",
    ".zsh",
    ".zst",
]
colorz = [
    (240, 248, 255),
    (250, 235, 215),
    (0, 255, 255),
    (127, 255, 212),
    (240, 255, 255),
    (245, 245, 220),
    (255, 228, 196),
    (255, 235, 205),
    (165, 42, 42),
    (222, 184, 135),
    (95, 158, 160),
    (127, 255, 0),
    (210, 105, 30),
    (255, 127, 80),
    (100, 149, 237),
    (255, 248, 220),
    (220, 20, 60),
    (0, 255, 255),
    (184, 134, 11),
    (169, 169, 169),
    (189, 183, 107),
    (139, 0, 139),
    (85, 107, 47),
    (255, 140, 0),
    (153, 50, 204),
    (139, 0, 0),
    (233, 150, 122),
    (143, 188, 143),
    (0, 206, 209),
    (255, 20, 147),
    (105, 105, 105),
    (30, 144, 255),
    (255, 250, 240),
    (34, 139, 34),
    (255, 0, 255),
    (220, 220, 220),
    (248, 248, 255),
    (255, 215, 0),
    (218, 165, 32),
    (128, 128, 128),
    (0, 128, 0),
    (173, 255, 47),
    (128, 128, 128),
    (240, 255, 240),
    (255, 105, 180),
    (205, 92, 92),
    (255, 255, 240),
    (240, 230, 140),
    (230, 230, 250),
    (255, 240, 245),
    (124, 252, 0),
    (255, 250, 205),
    (173, 216, 230),
    (240, 128, 128),
    (224, 255, 255),
    (250, 250, 210),
    (211, 211, 211),
    (144, 238, 144),
    (211, 211, 211),
    (255, 182, 193),
    (255, 160, 122),
    (32, 178, 170),
    (135, 206, 250),
    (119, 136, 153),
    (176, 196, 222),
    (255, 255, 224),
    (0, 255, 0),
    (50, 205, 50),
    (250, 240, 230),
    (255, 0, 255),
    (102, 205, 170),
    (186, 85, 211),
    (147, 112, 219),
    (60, 179, 113),
    (123, 104, 238),
    (0, 250, 154),
    (72, 209, 204),
    (199, 21, 133),
    (245, 255, 250),
    (255, 228, 225),
    (255, 228, 181),
    (255, 222, 173),
    (253, 245, 230),
    (128, 128, 0),
    (107, 142, 35),
    (255, 165, 0),
    (255, 69, 0),
    (218, 112, 214),
    (238, 232, 170),
    (152, 251, 152),
    (175, 238, 238),
    (219, 112, 147),
    (255, 239, 213),
    (255, 218, 185),
    (205, 133, 63),
    (255, 192, 203),
    (221, 160, 221),
    (176, 224, 230),
    (188, 143, 143),
    (65, 105, 225),
    (139, 69, 19),
    (250, 128, 114),
    (244, 164, 96),
    (46, 139, 87),
    (255, 245, 238),
    (192, 192, 192),
    (135, 206, 235),
    (106, 90, 205),
    (112, 128, 144),
    (255, 250, 250),
    (0, 255, 127),
    (70, 130, 180),
    (210, 180, 140),
    (0, 128, 128),
    (216, 191, 216),
    (255, 99, 71),
    (64, 224, 208),
    (245, 222, 179),
    (255, 255, 255),
    (245, 245, 245),
    (255, 255, 0),
    (154, 205, 50),
    (25, 225, 212),
]


def color() -> tuple[int, int, int]:
    return random_choice(colorz)


if __name__ == "__main__":
    dc = []
    for ext in extensions:
        r, g, b = color()
        exc = f"*{ext}=05;38;2;{r};{g};{b}"
        dc.append(exc)
    dc_str = ":".join(dc)
    dircolors = f"""
LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:{dc_str}"
export LS_COLORS
"""
    Path("/data/data/com.termux/files/home/.ls_colors").write_text(dircolors, encoding="utf-8")
